### ISSUE TITLE
Script scope clashes with that of the @requires

### ISSUE THREAD

**Issue by chocolateboy** [Tampermonkey/tampermonkey#1008]
In Greasemonkey (v4.9) and Violentmonkey (v2.12.7), it's possible to declare local variables at the top level of a userscript without worrying about name conflicts with `@require` dependencies because they are evaluated in a distinct (nested) scope/IIFE. That doesn't appear to be the case with Tampermonkey, which can cause accidental clashes.

### jquery-test-plugin.js

```javascript
function foo () { ... }
function bar () { ... }

// ...

jQuery.fn.test = function () {
    if (something) {
        foo(this)
    } else {
        bar(this)
    }
}
```

### example.user.js

```javascript
// ==UserScript==
// @name          Non-Portable Userscript
// @include       *
// @require       https://code.jquery.com/jquery-3.5.1.min.js
// @require       https://example.com/jquery-test-plugin.js
// ==/UserScript==

const foo = () => 42

console.log(foo()) // 42
```

## Actual Behavior

```javascript
const foo = () => 42 // Uncaught SyntaxError: redeclaration of function `foo` 

console.log(foo()) 
```

## Specifications

- **Tampermonkey**: 4.11.6117
- **Firefox**: v79.0
- **OS**: Linux (Arch)

**Comment by derjanb** [comment]
This is how it worked in Greasemonkey 3.x  and in Tampermonkey since it exists. A change may break a lot of existing userscripts. 
A potential workaround is to change the required script to use IIFE or to wrap the userscript into a IIFE which also allows to make use of "use strict;".

**Comment by chocolateboy** [comment]
> A change may break a lot of existing userscripts.

How so? This hasn't been the case (for this feature) with Violentmonkey and Greasemonkey v4. Note the userscript scope is **nested** within that of the `@require`d dependencies, not isolated from it.

**Comment by derjanb** [comment]
> How so? This hasn't been the case (for this feature) with Violentmonkey and Greasemonkey v4

See Tampermonkey exists longer than GM4 and VM and as I said the feature works like it worked in GM3 since `@require` was invented. This means from my point of view there is a good chance that there are scripts that somehow rely on the current behavior.

Fortunately this is a "good-natured" problem. Developers will instantly notice if something fails because of this during development. And even if not, then a simple IIFE added to the userscript solves the issue while having maximum flexibility by not doing it by default.

Fun Fact: you can pass arguments to `require`d scripts 🙈 Not sure if this works at the others...

```JS
// ==UserScript==
// @name         require argument
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match       https://example.com
// @require     1.user.js
// @grant        none
// ==/UserScript==

('bar')
```

1.user.js
```JS
console.log
```
