### ISSUE TITLE
Feature request:  support for `Right-click`  the `Dashboard` button of Popup-UI

### ISSUE THREAD

**Issue by dnknn** [Tampermonkey/tampermonkey#1133]
![image](https://user-images.githubusercontent.com/10995302/106371231-e4d2cb80-639c-11eb-8c46-3f073891fc45.png)

### 👆 Can support to use `Right-click` to Open dashboard with the current tab's URL used as filter ❓

- Yes, This feature allows you to not use hotkey 👇
`chrome://extensions/shortcuts#:~:text=Open dashboard with the current tab's URL used as filter`

- Yes, You can also refer to [Stylus extension](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne), its Popup-UI manager/dashboard button, which also has this feature, i.e. 

1. `Left-click`:  Open dashboard/manager.
2. `Right-click`: Open dashboard/manager with the current tab's URL used as filter.

**Comment by jb222** [comment]
This works a bit clumsy in MacOS because right-clicking shows the "Inspect" label for opening DevTools. 
I guess it also should show some descriptive text like "Open dashboard with current URL" so the user can make a choice.

![rightclicking dashboard](https://user-images.githubusercontent.com/61352184/107424841-6bff0c80-6b1e-11eb-9cdf-60d49d446f11.png)

**Comment by dnknn** [comment]
> This works a bit clumsy in MacOS because right-clicking shows the "Inspect" label for opening DevTools.

No, It has nothing to do with it, and there is no conflict at all.It belongs to one definition. Tampermonkey supports right-click, and it will override UA's right-click.



> I guess it also should show some descriptive text

Yes, but it is best to be brief.
