### ISSUE TITLE
GM_registerMenuCommand now registers context menu in Firefox

### ISSUE THREAD

**Issue by lainverse** [Tampermonkey/tampermonkey#1167]
My script registers a menu command to be displayed in TM's menu, but now it pollutes context menu on every single page as well even though have no business to be there. Is there a way to fix this from my side? I don't see anything in documentation related to adding to context menu in the first place or option not to do so.

From documentation:
```
GM_registerMenuCommand(name, fn, accessKey)
Register a menu to be displayed at the Tampermonkey menu at pages where this script runs and returns a menu command ID.
```

From changelog:
>  Add Userscript menu commands to the page's context menu

## Expected Behavior
GM_registerMenuCommand adds menu command only into TM button's menu and only there.

## Actual Behavior
GM_registerMenuCommand adds menu command into TM button's menu AND into page's context menu.

## Specifications

- Firefox: 86.0b9
- TM: 4.12.6130
- OS: Windows 10

## Script

https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes/

**Comment by derjanb** [comment]
> as well even though have no business to be there

So it's not running there? If so then this is a bug which might be fixed at the latest BETA version.

An option to disable the new behavior was added in #1164

**Comment by lainverse** [comment]
Beta feature partially solves the problem since it comes enabled by default and affects all scripts and when you disable it you do so for all scripts as well. Previous versions of TM hasn't affected context menu, Violentmonkey does nothing there as well and Greasemonkey doesn't support this command anymore (thus doesn't register context menu action either), so I don't understand what was the reason to add it there. If you think this absolutely have to add context menu, then maybe do so in GM.registerMenuCommand which current versions of Greasemonkey support?

**Comment by derjanb** [comment]
> Beta feature partially solves the problem since it comes enabled by default and affects all scripts and when you disable it you do so for all scripts as well. 

Yes, you can decide whether you want to see menu commands at the context menu or not only globally. This is because some Tampermonkey versions might not support adding entries to the page's context menu and I don't want to introduce a new type of menu command.

> I don't understand what was the reason to add it there.

Scripts usually add menu commands so that the user can trigger a certain script functionality. Having this at the context menu shortens the way to the menu command. You don't need to click at the Tampermonkey icon anymore but can simply open the context menu.

> even though have no business to be there.

Why does the script register a menu command if it does nothing at this page?

> or at least add an option for scripts to exclude themselves from this behavior

I wasn't aware that people are so annoyed by having another icon at the context menu which adds functionality that a script they installed offers. And I don't feel that the Tampermonkey entry bloats the context menu too much [1], but I might be wrong.
On the other hand Tampermonkey BETA with the context menu entry was rolled out to 410000 Chrome users and 370000 Firefox users and the number of complains I heard is low in view of these numbers. 

However, it makes perfect sense to make this user configurable

[1]
![image](https://user-images.githubusercontent.com/767504/110165580-6a5df700-7df3-11eb-84cf-7221613feed5.png)

**Comment by lainverse** [comment]
Considering GM which introduced this feature doesn't add records into context menu (including new `GM.` API) and neither VM does it only makes sense to introduce a new command specifically for context menu actions. Maybe even without this weird 3 level menu, but a way to add a new command either directly in Tampermonkey submenu or below it (with optional switch set to add into submenu by default) and option to add custom icon for convenience.

Well, it isn't too intrusive like this. Just got complains from some users of my script and don't really like the idea either. I'll recommend them to update to Beta and disable it in settings for now.

**Comment by derjanb** [comment]
I decided to keep the current behavior unless I get more complaints. Sorry. :-)
