### ISSUE TITLE
iOS 15 Support

### ISSUE THREAD

**Issue by sixiansheng** [Tampermonkey/tampermonkey#1258]
这个系统上可以运行扩展，因为他是全平台的，所以有新的开发计划吗？各位小伙伴

**Comment by derjanb** [comment]
I am reviewing this possibility.

However, I am still a little unsure whether there will be any fundamental changes to iOS Safari extensions due to the changes because of Manifest v3 and the newly founded [WebExtensions Community Group](https://www.w3.org/community/webextensions/2021/06/04/forming-the-wecg/).

After the deprecation of the legacy Safari Extensions, I already had to completely rewrite the Safari Support (Safari App Extensions), and will now have to do it again for the new Safari Extensions API (#1031).

**Comment by derjanb** [comment]
First investigation showed that [no persistent background page can be used at iOS](https://developer.apple.com/documentation/safariservices/safari_web_extensions/assessing_your_safari_web_extension_s_browser_compatibility#3584140). This means I have to rework Tampermonkey to support this first. This rework is also required for Manifest v3 support.

**Comment by happyman090** [comment]
Just letting you know that extensions are officially available now, meaning if iOS support is ready at some point, you will be able to release it.

**Comment by yeniugo** [comment]
You can upload to the app store and charge a fee to offset the cost of your account.

**Comment by xadamxk** [comment]
I already emailed you regarding this topic but I would be more than willing to cover the dev license fee for you @derjanb

**Comment by derjanb** [comment]
I already do have an Apple developer account. Thanks. The problem is that a lot of rework is necessary to support a non-persistent background page. See https://github.com/Tampermonkey/tampermonkey/issues/1258#issuecomment-875684806

**Comment by rusproject** [comment]
It would be awesome, any chances that iOS extension will became available this year?

**Comment by ydx1013** [comment]
iOS extension will become available this year?

**Comment by derjanb** [comment]
> iOS extension will become available this year?

I tend to say yes. ☺

**Comment by ililu2000** [comment]
iOS 上大家可以试试这个App
Maybe you can try this app on iOS Safari
https://apps.apple.com/us/app/userscripts/id1463298887

**Comment by xadamxk** [comment]
> iOS 上大家可以试试这个App Maybe you can try this app on iOS Safari https://apps.apple.com/us/app/userscripts/id1463298887

This is for MacOS, not iOS.

**Comment by newadventure079** [comment]
> > iOS 上大家可以试试这个App Maybe you can try this app on iOS Safari https://apps.apple.com/us/app/userscripts/id1463298887
> 
> This is for MacOS, not iOS.

It's also for iOS.  I installed it on my iphone last night

**Comment by willl** [comment]
> > iOS 上大家可以试试这个App Maybe you can try this app on iOS Safari https://apps.apple.com/us/app/userscripts/id1463298887
> 
> This is for MacOS, not iOS.

The latest version has iOS/iPadOS support, in addition to macOS
See: https://github.com/quoid/userscripts#installation

And screenshot from the app store link
![image](https://user-images.githubusercontent.com/926823/149846734-0ac8eaed-f376-4399-ad55-e930f3303eb5.png)

**Comment by xadamxk** [comment]
Have there been any updates regarding iOS? @derjanb
I would love to have Tampermonkey on my mobile - all of these 3rd party alternatives suck.

**Comment by derjanb** [comment]
Kind of. 😇 
All preparations for Manifest v3 are going to help to create a real Safari Web Extension that will also run at iOS.

**Comment by lhliddal** [comment]
How long do you believe it is until the extension is ready? And will you sell licenses or make it freely available? 
Kind regards

**Comment by Idanox** [comment]
Any news?

**Comment by Xaositek** [comment]
Was this ever reconsidered or just allow UserScripts to take over the mobile market?

**Comment by derjanb** [comment]
This is one of my next steps. I needed to convert Tampermonkey to a non-persistent first, which was done for Firefox Android now and I already bought an IPad to be able to develop and test Tampermonkey for iOS.

**Comment by Seele0oO** [comment]
Userscript does not seem to provide complete support, and some scripts such as [bilibili evo](https://github.com/the1812/Bilibili-Evolved) do not run properly.
As [reference commit](https://github.com/the1812/Bilibili-Evolved/issues/3642), it does not provide full support.
Thanks again derjanb.

**Comment by alexchexes** [comment]
Hello, @derjanb! Any news on this?
Checking out this topic for two years and haven't lost hope of seeing a full-featured (or at least half-featured) Tampermonkey for iOS.

Thank you for your work, by the way. I supported you with a small amount recently ;)

**Comment by derjanb** [comment]
The new Tampermonkey (web) extension is working fine on macOS. I now have to check iOS...

**Comment by Idanox** [comment]
Will it be available for the iOS 18 release or later?

**Comment by alexchexes** [comment]
> ... I now have to check iOS...

@derjanb Any update on this, pleeeeease? 🥺

**Comment by sixiansheng** [comment]
> > ... I now have to check iOS...
> 
> @derjanb Any update on this, pleeeeease? 🥺

I'm afraid there's little hope. As you know, all browsers are now pushing for the new V3 extension protocol. I doubt the extensions we've written have been released yet. They've probably been stillborn.😨

**Comment by EffeF** [comment]
> I now have to check iOS

Any updates? It was unpinned because it's close to release, right? 🥲

**Comment by derjanb** [comment]
Unpinned, because I needed to pin another frequently asked question, but...

![s](https://github.com/user-attachments/assets/603ced00-76c5-4ba2-947b-d652e66e6b81)

**Comment by alexchexes** [comment]
OH. MY. HOLY. MOLY. GUACAMOLE. GOSH.
I CAN'T BELIEVE IT'S FINALLY HAPPENING. Tampermonkey is coming to iOS, fellas!! Uck yeah!!

**Comment by Xaositek** [comment]
Well this is an exciting development! TestFlight available yet?

**Comment by derjanb** [comment]
## It's done! 

[iOS support is there!](https://apps.apple.com/us/app/tampermonkey/id6738342400)

The macOS version is still in review, but it should be available soon.

For now Tampermonkey Safari (WebExt version) has these two known issues: #2252 and #2253
Please create a new issue if you find something else.

## Free licenses

Again I charge a small fee for this version, because I had to buy Apple hardware to get this done. I hope you understand.
However, for people that

 * donated in the past
 * helped me by posting Github issues and comments
 * develop popular scripts

I'll give a free license.

Just register your email on the [Tampermonkey website](https://tmnk.net/promo.php) and follow the steps explained at the email you'll receive.

## Request for help with the macOS version

I'm not entirely sure if there is one more issue in the macOS version. I got everything working on my end. Especially `GM_notification` was difficult to get working in iOS, but it's working now.
So I worked on renaming the Safari App based Tampermonkey version to "Tampermonkey Classic", uploaded and published it.
Back at work on the WebExt version, notifications stopped working with

`"UNErrorDomain" error 1, the operation couldn't be completed"

I think this is maybe related to renaming the app, which got the notification permission long time ago, but all tried [ways to make macOS forget the extension](https://stackoverflow.com/questions/70039047/unable-to-request-authorization-for-local-notifications-on-macos) didn't work. 
So you could do me a favor and try the macOS version, once it's available, and tell me if notifications are working for you. I'll keep you post ed here once this happens.

**Comment by zxkmm** [comment]
Thanks, just bought it! It's not that cheap in my country based on average purchasing capabilities, but I still bought it to show some supports for nice work.

**Comment by Xaositek** [comment]
Instant Buy! Thank you so much for doing this @derjanb!

**Comment by alexchexes** [comment]
Instant Buy as well 😂 It's just like an upcoming birthday present lol.
Btw, @derjanb, you could set a price much higher than $2.99 for the launch day — we'd still buy it to support you! ;) Thank you so much for this long-awaited release

**Comment by alexchexes** [comment]
And yes, I just tested it — all the essentials work fine: script sync with Google Drive, and scripts that were expected to work on an iPhone are working perfectly. Great job!!!

**Comment by ted1030** [comment]
Finally! Instant buy!
It’s been such a long time, but I’ve finally seen Tampermonkey on iOS!
I've tested the API GM_setValue, GM_getValue works fine.

But I encountered a problem. if the content of a @resource changes, GM_getResourceText will get the old content.
Manually updating or deleting the resource at the external setting of the userscript is not working, which is the same on Windows Chrome. At this point I can do hard refresh by right click the refresh button, but it is impossible on iOS Safari.
I've found a workaround that visit the resource url directly will force the cache to be updated and GM_getResourceText can get the lastest content.

**Comment by derjanb** [comment]
@ted1030 

The "Delete" button only deletes the resource and Tampermonkey relies on browser caching mechanisms to get the resource again. 
"Update" should request it in a way that makes the browser not use the cache.

![image](https://github.com/user-attachments/assets/2403e93a-6eb1-46ba-9061-a2dd31f23301)

**Comment by hguandl** [comment]
Nice work! As a user of Tampermonkey Classic, I wonder whether there is an option to upgrade instead of buying a new App. As far as I know, App Store supports [App Bundles](https://developer.apple.com/app-store/app-bundles/). For example, if there is a bundle containing both Tampermonkey and Tampermonkey Classic, classic users would pay `price of bundle` minus `price of Tampermonkey Classic`. I would really appreciate it if there would be a little discount for classic users.

**Comment by micturkey** [comment]
> Nice work! As a user of Tampermonkey Classic, I wonder whether there is an option to upgrade instead of buying a new App. As far as I know, App Store supports [App Bundles](https://developer.apple.com/app-store/app-bundles/). For example, if there is a bundle containing both Tampermonkey and Tampermonkey Classic, classic users would pay `price of bundle` minus `price of Tampermonkey Classic`. I would really appreciate it if there would be a little discount for classic users.

Agree!
I believe the new app is well worth the price, but it would be even better if there were a discount for existing classic users. Such a gesture would not only show appreciation for loyal users but also encourage more people to make the upgrade.

**Comment by ted1030** [comment]
> The "Delete" button only deletes the resource and Tampermonkey relies on browser caching mechanisms to get the resource again. "Update" should request it in a way that makes the browser not use the cache.

Thanks, I've retried the Update button and it works.

I have another question. Is it possible to add an option to determine whether the enabled state should be overwritten when importing from a backup?
Because some userscripts are targeted at mobile browsers rather than PC browsers.
Or a web extension doesn't have an ios Safari version, so we have to used an alternative userscript.
In these cases I want to sync the script content but exclude the enabled state.

**Comment by derjanb** [comment]
> Nice work! As a user of Tampermonkey Classic, I wonder whether there is an option to upgrade instead of buying a new App. As far as I know, App Store supports [App Bundles](https://developer.apple.com/app-store/app-bundles/). For example, if there is a bundle containing both Tampermonkey and Tampermonkey Classic, classic users would pay `price of bundle` minus `price of Tampermonkey Classic`. I would really appreciate it if there would be a little discount for classic users.

Thanks for the hint.

*The status for the following app bundle has changed to Waiting for Review.*

**Comment by derjanb** [comment]
## Request for help with the macOS version

I'm not entirely sure if there is one more issue in the macOS version. I got everything working on my end. Especially `GM_notification` was difficult to get working in iOS, but it's working now.
So I worked on renaming the Safari App based Tampermonkey version to "Tampermonkey Classic", uploaded and published it.
Back at work on the WebExt version, notifications stopped working with

`"UNErrorDomain" error 1, the operation couldn't be completed"

I think this is maybe related to renaming the app, which got the notification permission long time ago, but all tried [ways to make macOS forget the extension](https://stackoverflow.com/questions/70039047/unable-to-request-authorization-for-local-notifications-on-macos) didn't work. 

The macOS version is reviewed and available now.  So could someone do me a favor and try the macOS version, and tell me if notifications via `GM_notification` are working for you?

**Comment by alexchexes** [comment]
> So could someone do me a favor and try the macOS version, and tell me if notifications via GM_notification are working for you?

For me, `GM_notification` works in both Tampermonkey and Tampermonkey Classic.  
I already had `Tampermonkey Classic` installed back when it was just `Tampermonkey`. I just installed the new `Tampermonkey` as well and didn't even turn off "Tampermonkey Classic" during testing. Everything works fine, except that I had to manually enable notifications for Tampermonkey in the settings (there was no automatic prompt for it, although there was for Classic).

<img width="492" alt="Screenshot 2024-11-20 at 12 16 11" src="https://github.com/user-attachments/assets/5fec8d83-cf61-4b8a-b5f6-3b9a9646014e">

<img width="415" alt="Screenshot 2024-11-20 at 12 15 22" src="https://github.com/user-attachments/assets/6eea20e2-c9c6-4317-a940-def3c99e5d0e">

<img width="508" alt="Screenshot 2024-11-20 at 12 15 51" src="https://github.com/user-attachments/assets/b0bfa042-301b-4efa-93f3-a0079baade17">

Prompt for Classic because I tried `GM_notification` for the first time:

<img width="379" alt="Screenshot 2024-11-20 at 11 22 40" src="https://github.com/user-attachments/assets/5fc483cf-e9cd-47f7-8e70-d965a21d9945">


```js
// ==UserScript==
// @name         Test GM_notification
// @namespace    http://tampermonkey.net/
// @version      2024-07-03
// @description  Test GM_notification
// @author       You
// @match        https://www.tampermonkey.net/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=tampermonkey.net
// @grant        GM_notification
// ==/UserScript==

(function() {
    'use strict';
    console.log('Tampermonkey NOT classic');

    const test_GM_notification = async () => {
        console.log('test_GM_notification NOT classic');

        GM_notification({
            text: "This is the notification message.",
            title: "Notification Title",
            url: 'https:/example.com/',
            onclick: (event) => {
                // The userscript is still running, so don't open example.com
                event.preventDefault();
                // Display an alert message instead
                alert('I was clicked!')
            }
        });

        const clicked = await GM.notification({ text: "Click me." });
        console.log('clicked', clicked);
    }

    setTimeout(function () {
        test_GM_notification();
    }, 500)
})();
```


macOS 14.6.1, MBPro M3 Pro.

**Comment by derjanb** [comment]
> Nice work! As a user of Tampermonkey Classic, I wonder whether there is an option to upgrade instead of buying a new App. As far as I know, App Store supports [App Bundles](https://developer.apple.com/app-store/app-bundles/). For example, if there is a bundle containing both Tampermonkey and Tampermonkey Classic, classic users would pay `price of bundle` minus `price of Tampermonkey Classic`. I would really appreciate it if there would be a little discount for classic users.

The App bundle is available now. Can someone who bought Tampermonkey Classic please check whether the pruce is the difference between Tampermonkey and Tampermonkey Classic? Thanks

https://apps.apple.com/app-bundle/tampermonkey-bundle/id1780757125

**Comment by chensiyue98** [comment]
> > Nice work! As a user of Tampermonkey Classic, I wonder whether there is an option to upgrade instead of buying a new App. As far as I know, App Store supports [App Bundles](https://developer.apple.com/app-store/app-bundles/). For example, if there is a bundle containing both Tampermonkey and Tampermonkey Classic, classic users would pay `price of bundle` minus `price of Tampermonkey Classic`. I would really appreciate it if there would be a little discount for classic users.
> 
> The App bundle is available now. Can someone who bought Tampermonkey Classic please check whether the price is the difference between Tampermonkey and Tampermonkey Classic? Thanks
> 
> https://apps.apple.com/app-bundle/tampermonkey-bundle/id1780757125

It will be 1 euro for the bundle in the Netherlands!
<img width="951" alt="image" src="https://github.com/user-attachments/assets/807b15dd-0f6c-4b94-be55-7e082b1523cc">

**Comment by derjanb** [comment]
> > > Nice work! As a user of Tampermonkey Classic, I wonder whether there is an option to upgrade instead of buying a new App. As far as I know, App Store supports [App Bundles](https://developer.apple.com/app-store/app-bundles/). For example, if there is a bundle containing both Tampermonkey and Tampermonkey Classic, classic users would pay `price of bundle` minus `price of Tampermonkey Classic`. I would really appreciate it if there would be a little discount for classic users.
> > 
> > 
> > The App bundle is available now. Can someone who bought Tampermonkey Classic please check whether the price is the difference between Tampermonkey and Tampermonkey Classic? Thanks
> > https://apps.apple.com/app-bundle/tampermonkey-bundle/id1780757125
> 
> It will be 1 euro for the bundle in the Netherlands! <img alt="image" width="951" src="https://private-user-images.githubusercontent.com/21059167/389188679-807b15dd-0f6c-4b94-be55-7e082b1523cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODU3OTEsIm5iZiI6MTczMjM4NTQ5MSwicGF0aCI6Ii8yMTA1OTE2Ny8zODkxODg2NzktODA3YjE1ZGQtMGY2Yy00Yjk0LWJlNTUtN2UwODJiMTUyM2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE4MTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyOGYxYjhjYWY3MmZhMDU2ZjgxZTM1YmM4MDdlZDI0NThjNGFmOGQ1OGE1NTUwNGE3NzlhM2I3NDlkMDg4MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h-outPG5m8m4jkGT2v6rbupYqDmvi6cDXRmMo6p91kg">

Great. So this is the upgrade path for Tampermonkey Classic users.

**Comment by ocd0711** [comment]
> > > > Nice work! As a user of Tampermonkey Classic, I wonder whether there is an option to upgrade instead of buying a new App. As far as I know, App Store supports [App Bundles](https://developer.apple.com/app-store/app-bundles/). For example, if there is a bundle containing both Tampermonkey and Tampermonkey Classic, classic users would pay `price of bundle` minus `price of Tampermonkey Classic`. I would really appreciate it if there would be a little discount for classic users.
> > > 
> > > 
> > > The App bundle is available now. Can someone who bought Tampermonkey Classic please check whether the price is the difference between Tampermonkey and Tampermonkey Classic? Thanks
> > > https://apps.apple.com/app-bundle/tampermonkey-bundle/id1780757125
> > 
> > 
> > It will be 1 euro for the bundle in the Netherlands! <img alt="image" width="951" src="https://private-user-images.githubusercontent.com/21059167/389188679-807b15dd-0f6c-4b94-be55-7e082b1523cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODU3OTEsIm5iZiI6MTczMjM4NTQ5MSwicGF0aCI6Ii8yMTA1OTE2Ny8zODkxODg2NzktODA3YjE1ZGQtMGY2Yy00Yjk0LWJlNTUtN2UwODJiMTUyM2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE4MTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyOGYxYjhjYWY3MmZhMDU2ZjgxZTM1YmM4MDdlZDI0NThjNGFmOGQ1OGE1NTUwNGE3NzlhM2I3NDlkMDg4MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h-outPG5m8m4jkGT2v6rbupYqDmvi6cDXRmMo6p91kg">
> 
> Great. So this is the upgrade path for Tampermonkey Classic users.

Does the US not have a bundle? Classic user upgrade or $2.99?

**Comment by derjanb** [comment]
The bundle is available in all countries.

![image](https://github.com/user-attachments/assets/827e1656-8b2c-4320-b94a-7a5dd885804f)

When creating a bundle one only can add apps, set the price and country availability, add some screenshots and description and that's it. 

So please contact Apple support with your Tampermonkey Classic purchase ID and ask them for help.

**Comment by xlilu** [comment]
UI bug in Dark Mode
