### ISSUE TITLE
Lost all scripts after TamperMonkey update + Chrome crash

### ISSUE THREAD

**Issue by munael** [Tampermonkey/tampermonkey#1265]
(Please fill out the issue template with your details)

## Expected Behavior
TamperMonkey update does not require a Chrome restart, and if it needs it it shouldn't lead to corrupting the extension if the browser crashes.

## Actual Behavior
TamperMonkey update required a Chrome restart. I dismissed it. Later, browser crashed. Now, TM needed to be "repaired" and all scripts are gone.

## Specifications

- Chromium: 92.0.4515.51
- TM: 4.13
- OS: Win10 19042

## Script

N/A

**Comment by derjanb** [comment]
Unfortunately there is nothing an extension can do when the browser profile gets corrupted and/or the extension storage is reset by the browser.

**Comment by munael** [comment]
Only this extension got corrupted, though :/

**Comment by Destroy666x** [comment]
I don't want to create another issue since there are a few to this, so let me try asking here first @derjanb 

So, my Chrome crashed, this was for some reason the only extension that got broken. I clicked "refresh extension" and basically all of its data was gone. What can I do now considering that:
- I had Google sync in theory, but apparently in my drive there's only what I imported on this new laptop one year ago and it didn't get updated for some reason. Why didn't it get updated? Was I missing some kind of configuration? Why was it missing considering that old laptop backed up everthing correctly?
- files are likely gone, I'm not sure what to check in the 1st place as I can't find what is mentioned in other issues with Everything

I assume nothing, not a big deal since I just added like 2 - 3 external scripts that aren't in the backup, I'm asking though in case I'll run into a similar issue again.
