### ISSUE TITLE
duplicate userscript sync in firefox

### ISSUE THREAD

**Issue by heroboy** [Tampermonkey/tampermonkey#1268]
(Please fill out the issue template with your details)

## Expected Behavior
Always keep same script only one instance installed.

## Actual Behavior
At first, I installed the script using copy the code into the tampermonkey editor. After this issue happened, I tried delete this script, and install using the `Install from URL` in the tampermonkey. Because I hope the tampermonkey will treat the install url as the unique id of the script to avoid the duplication.

Everyday when I open the firefox, there are large probability, the script has 2 instance installed(maybe delayed some seconds, because the firefox sync).  Then I delete one of them.

Sometimes, after the firefox long running, the script instance will become 2. 

Sometimes, when I opened the firefox , the script instance is 3. And sometimes it is one enabled,and one disabled(this maybe I may miss click to disabled the script at first, when I tried to delete it).

I have 3 PCs running the firefox with same account. They maybe running at same time. Maybe they sync each other cause this problem. 
When I delete the duplicated script, I do nothing with other pc, maybe they are running with 2 instance of the script. Maybe they upload the duplication info to the cloud again.

I think a script always has an unique id, how this issue occur?

## Specifications

- firefox: 89.0.1
- TM: v4.13.6136
- OS:  Windows 10

## Script
https://gitee.com/likexia/Evolve/raw/master/scripts/evolve.js

**Comment by JAGulin** [comment]
I don't think script sync is active unless you activated it. Can you check and report your settings?
https://www.tampermonkey.net/faq.php#Q105

Can you also clarify that you're actually talking about the number of scripts listed in the Dashboard, not about the number shown on the badge? What is the URL for your install, where you can see the active scripts (to make sure you have a proper TM)?

The fact that you were able to install two copies I think was fair use-case and no bug. You did that intentionally. The strange part is where you get more scripts installed without intention. Question would be if that is due to TM or Firefox or something else.

> I do nothing with other pc, maybe they are running with 2 instance of the script.
I suppose it'd be easy for you to check that. If not, that discards the sync idea, I think.
Could you try disabling sync temporarily, like logging out from the other machines or disabling the TM plugin there.

**Comment by heroboy** [comment]
> The fact that you were able to install two copies I think was fair use-case and no bug. You did that intentionally. 

No. When you open the same userscript url. You will get the reinstall or update button. It is not easy to intentionally installe duplicate scripts.

> Could you try disabling sync temporarily, like logging out from the other machines or disabling the TM plugin there.

I don't do this. Because I think it is useless.
1. I have to wait many days to check is it have effect.
2. I guess disable sync or disable TM doesn't clear the sync data.(I have click the sync reset, nothing happened.)
3. Although I have many PCs turn on samething. But not all time. 
4. Race condition problem is complex.

**Comment by JAGulin** [comment]
>  I installed the script using copy the code into the tampermonkey editor. After this issue happened, I tried delete this script

I misread this earlier. So the duplication problem appeared even when you only installed one script. 
The fact that Userscript sync is enabled through Browser Sync is useful to know.

> I have posted my TM version.

I meant to ask for the actual install, same version can be installed in different ways. But this was a tangent, not critical to clarify.

> I don't do this. Because I think it is useless.

20 days passed already without solution, but if you prefer doing nothing, that's ok by me. Perhaps there's enough for a developer with code access to analyse as is.

For the interested...
I would otherwise suggest to disable script sync, uninstall all copies of the script, then clear sync and keep it disabled.
Do the same for the other machines.
Now go back to first machine: Activate sync. Install script once from URL. 
With only one machine syncing, this should be fine. Wait as many days as you like to confirm.
Then activate sync on second machine. Don't install script, let the sync install it for you. Confirm.
Then same on third machine. 

This plugin might show what the sync items are.
https://addons.mozilla.org/en-US/firefox/addon/about-sync/

I looked at the user script too. Here's the non-raw link.
https://gitee.com/likexia/Evolve/raw/master/scripts/evolve.js
At a quick glance I didn't see anything that would cause trouble, although the namespace could be changed.

**Comment by heroboy** [comment]
I tried installed "about sync", and find this:
```json
{
"0f8d54dd-bdd2-4912-8f25-083f6aecdee1@v2": "{\"url\":\"https://gitee.com/likexia/Evolve/raw/master/scripts/evolve.js\",\"options\":{},\"uuid\":\"0f8d54dd-bdd2-4912-8f25-083f6aecdee1\",\"lastModified\":1625057102145}",
	"d5acbb87-753d-4f7b-8999-5282dac3aeb2@v2": "{\"url\":\"https://gitee.com/likexia/Evolve/raw/master/scripts/evolve.js\",\"options\":{},\"uuid\":\"d5acbb87-753d-4f7b-8999-5282dac3aeb2\",\"lastModified\":1625105203956}"
}
```
And actually it installed two of it now.
After I delete one, and force sync again, then:
```json
{
"0f8d54dd-bdd2-4912-8f25-083f6aecdee1@v2": "{\"options\":{\"removed\":true}}"
}
```



And I will try to disabled the sync for a moment to fix this problem.
But I also wonder how this happened. 
Sometime I find some useful script, I installed it on one my pc. And then switch to another pc, bacause the sync is not fast, I install the script again. Maybe I copy and paste to install the script. 
At this time, it is ok if the script become duplicate. But when I deleted this script again and again, why TM can't aware this.

It is interesting that it didn't happen that the two copied scripts being deleted both. Because on one pc upload the remove A version script, and another pc upload the remove B version. Then when synced, they both be deleted.

**Comment by heroboy** [comment]
Actaully disable sync doesn't delete the sync data. 
But I will coninute to post the sync data here to log and to analyze what cause the problem.

**Comment by heroboy** [comment]
Now I am on another pc. There are two instance of "Evolve"
![image](https://user-images.githubusercontent.com/54468/124750835-85cf3f00-df58-11eb-9cb5-d16b8e57af30.png)

I installed about sync. The data is
```json
{
   "d5acbb87-753d-4f7b-8999-5282dac3aeb2@v2": "{\"url\":\"https://gitee.com/likexia/Evolve/raw/master/scripts/evolve.js\",\"options\":{},\"uuid\":\"d5acbb87-753d-4f7b-8999-5282dac3aeb2\",\"lastModified\":1625105203956}",
   "0f8d54dd-bdd2-4912-8f25-083f6aecdee1@v2": "{\"options\":{\"removed\":true}}"
}
```
And I use the dashboard to see the script's UUID. One of them is "0f8d54dd-bdd2-4912-8f25-083f6aecdee1"
![image](https://user-images.githubusercontent.com/54468/124751005-b911ce00-df58-11eb-9560-7c221d0c46b8.png)
Apparently, TM ignored the "removed" sync data.

**Comment by heroboy** [comment]
I open my third pc. The only one installed "evolve" is "0f8d54dd-bdd2-4912-8f25-083f6aecdee1".

**Comment by heroboy** [comment]
As at first I installed this script via copy&paste source code, why this script became synced?

**Comment by JAGulin** [comment]
"0f8d" seems to on every machine, perhaps that's the "legitimate" one, installed from URL. Are the other variants listing the same URL under Update URL (in script settings tab)?

> As at first I installed this script via copy&paste source code, why this script became synced?

I suppose it picks up on the DownloadURL and uses that to sync. Each manual install however giving a unique copy (UUID). In this case it causes problems, but I still think there are legitimate cases to have copies installed (if done so manually). 

From what I understand, the sync is only passing that download url, so local changes would not transfer. The value of syncing scripts that were pasted in (possibly edited) might then be low. 


Changing name or Url might interfere with sync, but adding a translation should be safe. If you can identify the "copy paste" variants, you could add a more identifiable name. 
// @name:en      Evolve:d5acbb87

If you can't delete the scripts, and the multiple scripts interfere, you can instead try to empty the script function (keep the initial comment block) to neutralize it. There should come to an equilibrium where no new scripts add up, and where most copies do nothing. I'd suggest to keep the script installed from URL synced unchanged.

> Actaully disable sync doesn't delete the sync data.

I thought the "Sync reset" button would.

**Comment by heroboy** [comment]
Now I have two "evolve" on my machine.
I tried:
1. turn on sync in TM.
2. sync reset
3. remove one of the script
4. restart browser. (Maybe this was so quick. the removed sync data was not uploaded?)
5. script become two. (when browser just started, I open popup menu of TM, and notice "xxxx sycned,xxx 1 script imported(maybe it is exprted, I forget)")
And I tried 3-4 many times.

At last I notice there is a recycle bin in TM. I delete the script in recycle bin again. Restart browser, then there's no duplicate script.

**Comment by heroboy** [comment]
Look like TM is totaly mess up with local data, remote data and uncommited local change.
Don't want to only fix my problem. I think I can always clear all things, reset all things to fix this.
I post this issue is want to fix this bug in TM.

**Comment by derjanb** [comment]
>At first, I installed the script using copy the code into the tampermonkey editor. After this issue happened, I tried delete this script, and install using the Install from URL in the tampermonkey. Because I hope the tampermonkey will treat the install url as the unique id of the script to avoid the duplication.

No, script installations are not unique by installation URL, but namespace and script name. However this is a lax rule that is not enforced. That's why it is possible to install two scripts at 2 computers (they each get a unique ID), then turn on sync and get two scripts at each computer, because sync only acts on the unique scripts IDs.

>Everyday when I open the firefox, there are large probability, the script has 2 instance installed(maybe delayed some seconds, because the firefox sync). Then I delete one of them.

4.14.6141 might improve this a little bit. Tampermonkey didn't trigger a sync when a script was moved to trash but when it was deleted from trash. This could lead to confusion and is fixed at the most recent beta versions.

Can you please check whether 4.14.6141 fixes your problem? Thanks.

**Comment by heroboy** [comment]
@derjanb My current TM version is 4.13.6136. I doesn't see any update.
Should I install the beta version on https://www.tampermonkey.net/ ?

**Comment by heroboy** [comment]
By the way, if TM receive a `{removed:true}` sync data, what the script should be done? Remove to recycle bin or totaly delete it?

**Comment by derjanb** [comment]
> if TM receive a {removed:true} sync data, what the script should be done? 

It should be moved to trash and being ignored for all further sync actions.

> And as you mentioned the "time", you doesn't set a lastModified like time field in the remove sync data.

Good catch! This was broken in 2019 🙈 and fixed in 4.14.6141 as well.

**Comment by heroboy** [comment]
I didn't update the latest beta version. But this problem not happened again. Maybe I had did something totally removed it.
So I can't help you to reproduce this issue. If you think your previous code would cause this problem, and the latest version fixed this. You can close this issue.

**Comment by PriceHu** [comment]
Hello there, I'd like to provide some information regarding this issue **but on Chrome**. I've now resolved it but I think what I found may be useful.

I was facing the exact same issue with TM and browser synced scripts on Chrome. I've seen multiple scripts reappearing after deleted and trash cleaned. I'm currently using TM stable 4.14 from Chrome Webstore, but I've been experiencing this issue for months, so this may have started from 4.13 or earlier. To resolve this, I've clicked `Reset` button and then disabled sync function on all my devices except my desktop. Then I deleted unwanted scripts on my desktop, clicked `Reset`, clicked `Sync Now` and restarted browser, but it didn't work. I went to `chrome://sync-internals/` and found that scripts I deleted were actually still there, even if I cleaned trash and reset in TM. To actually cleanup these data, I exported my data and clicked `Factory Reset` in TM. Now all things were gone and after I re-imported my data, everything seems to work fine.

After doing all above, now if I click `Reset` in the control panel, I can see in `chrome://sync-internals/` that synced scripts are all gone. I suspect the issue was that TM was not able to delete data already synced to browser. When it resync scripts, it just grab all things in browser sync data. To check if this behavior still exists, I did a little research as following:

I chose a little script from https://greasyfork.org/en/scripts/405130-%E6%96%87%E6%9C%AC%E9%80%89%E4%B8%AD%E5%A4%8D%E5%88%B6. After installed and synced, I can see it as this:

![image](https://user-images.githubusercontent.com/21653481/154145125-88f6cfab-b6f2-446d-bdd9-e52248d82fb6.png)
![image](https://user-images.githubusercontent.com/21653481/154145164-4306965e-9ab8-496b-8656-0c91ac2263eb.png)

It was also in Chrome Sync data. Then I did a normal delete: **click delete and clean the trash**. Then I go to settings and clicked Sync Now to make sure chrome sync data was up to date. In `chrome://sync-internals/`, I can see that the sync was committed. But when I searched using the extension ID, it was still there:

![image](https://user-images.githubusercontent.com/21653481/154146750-8983b043-ca3a-4d3a-9ac4-3c3d6dc5da49.png)

This entry has no `"IS_DEL": true`. And I found only the following:

```
{
    metadata: {
        "is_deleted": false,
    ),
}
```

I was only able to remove this entry by clicking Reset and then Sync Now.

I hope this information would be helpful.
