### ISSUE TITLE
[Cent Browser] Tampermonkey does not work at multilogin tabs

### ISSUE THREAD

**Issue by dnknn** [Tampermonkey/tampermonkey#1295]
```js
	chrome://extensions/?id=dhdgffkkebhmkfjojejmpbldmpobfkfo
```

> Screenshot from the Internet	[imageScreenshotLiveDemo](https://user-images.githubusercontent.com/10995302/126843547-8b56e08f-3323-4300-8359-8a22bf764810.png)

![217_24053010](https://user-images.githubusercontent.com/10995302/126843494-50262a49-f014-4282-b63e-7318192498d0.png)

Then, just enter the **_incognitol mode_** and open the web page to test...

## Expected Behavior
- 	- 	-  ON☑ : Can work! (just like Violentmonkey)

## Actual Behavior
- 	- 	-  ON☑ : Can not work ..... (It is exactly the same as disabling Tampermonkey)

---------------
- Chromium: 80-86-90
- TM: All versions, at least the last 1 year.
- OS: Win10

**Comment by 7nik** [comment]
TM 4.13 and TM Beta 4.14.6142, Chromium 91, KDE Manjaro. TM works, scripts run with no errors.

**Comment by dnknn** [comment]
> TM 4.13 and TM Beta 4.14.6142, Chromium 91, KDE Manjaro. TM works, scripts run with no errors.

Thank you for your reminder, I tested and verified again and found that there is indeed no problem.

The problem appears in the fork browser of Chromium similar to this feature,

**Comment by dnknn** [comment]
But having said that, the function can be fixed/enhanced, I think it’s a problem with the API, because Violentmonkey is normal.

This is the browser : 　　　　　　http://centbrowser.com/history.html

I open this issue, if the author does not want to support this issue, please close it directly.

**Comment by derjanb** [comment]
Tampermonkey gets no navigation or other events from multilogin tabs. 🤷

Not sure how they implemented this mode, but no new Tampermonkey background page is started, like it is done when a regular incognito tab is created.

Other extensions might work because they don't use [split mode](https://developer.chrome.com/docs/extensions/mv2/manifest/incognito/#split) to secure potentially sensitive data from incognito mode tabs.

![image](https://user-images.githubusercontent.com/767504/128907458-8cc7347f-29c8-401b-ad45-2e9399742f99.png)

**Comment by derjanb** [comment]
I've posted a bug report at their forum: https://www.centbrowser.net/en/showthread.php?tid=4084

**Comment by derjanb** [comment]
> Thanks for your feedback.
> This is an old issue of multilogin tabs.
> We need to fully refactor this feature to solve it.
