### ISSUE TITLE
Scripts don't run on sites cached by Google

### ISSUE THREAD

**Issue by is-this-c** [Tampermonkey/tampermonkey#1349]
I checked that this issue doesn't exist in VM.

- Chromium: 94.0.4606.71
- TM: 4.13
- OS: Windows 10

**Comment by 7nik** [comment]
If you mean pages like [this](http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fgithub.com%2FTampermonkey%2Ftampermonkey&oq=cache%3Ahttps%3A%2F%2Fgithub.com%2FTampermonkey%2Ftampermonkey&aqs=chrome..69i57j69i58.1176j0j4&sourceid=chrome&ie=UTF-8) then, of course, it won't because the domain is `webcache.googleusercontent.com`.

**Comment by is-this-c** [comment]
So why can't Tampermonkey run scripts on sites cached by Google?

**Comment by is-this-c** [comment]
That doesn't fix the issue for me.

**Comment by is-this-c** [comment]
> It's because Brave redirects HTTPS. This one works in both.
> 
> ```js
> // ==UserScript==
> // @name         test google cache pages
> // @match        *://webcache.googleusercontent.com/*q=*github.com*
> // ==/UserScript==
> 
> alert(42);
> ```

Did you actually test this in Brave?  It doesn't run for me.

**Comment by 7nik** [comment]
Brave 1.30.89 Chromium: 94.0.4606.81 on KDE Manjaro and Brave 1.32.115 Chromium: 96.0.4664.93 on Win10, works on 
>  [this](http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fgithub.com%2FTampermonkey%2Ftampermonkey&oq=cache%3Ahttps%3A%2F%2Fgithub.com%2FTampermonkey%2Ftampermonkey&aqs=chrome..69i57j69i58.1176j0j4&sourceid=chrome&ie=UTF-8)
