### ISSUE TITLE
When opening a new tab can not see the source for implemented fix

### ISSUE THREAD

**Issue by grauziitisos** [Tampermonkey/tampermonkey#1377]
(Please fill out the issue template with your details)

## Expected Behavior
could see the implementation to evaluate it

## Actual Behavior
can not see

## Specifications
Version 96.0.4664.45 (Official Build) (64-bit)
4.1.13
- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script
I am not sure what is it, the same happened when tried to see the TM version
(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by 7nik** [comment]
Did I get right that you mean some userscript sometimes aren't listed in Devtools, tab Sources, subtab Page?
For example, the following userscript may not be listed in Devtools:
```js
// ==UserScript==
// @name         Disappearing script
// @match        http://www.example.com/
// ==/UserScript==

console.log("I have no source");
```

I could find only [this](https://stackoverflow.com/questions/31862344/chrome-developer-tools-do-not-show-all-javascript-files-any-more) and there is no solution, just a workaround - reload the page with opened devtools. 
My thoughts are that it happens because such scripts don't contain a code that will be run after the script execution, and so the script can be completely removed from memory, and thus it goes from Sources.

**Comment by grauziitisos** [comment]
Happy new year and thank you for caring!
Forgive me please for not responding.

Yes, I meant exactly that, for example jQuery in this sample case was not visible in sources.

However I tried to reproduce, but now it IS visible. Chrome has updated some times during this time, so maybe an update fixed it or something. Not sure, sorry.

However, thank you for detailed and quick response and keep up the awesome contribution you are doing. Thank you very much!
![image](https://user-images.githubusercontent.com/85872382/148135537-ce04027b-0ed7-4243-aabc-8c6b71c74fd0.png)
