### ISSUE TITLE
Cross Origin Permission Request spam

### ISSUE THREAD

**Issue by ZdrytchX** [Tampermonkey/tampermonkey#1572]
## Issue:

Cross Origin Request Access -> Denying access causes extension to re-request at a later time, sometimes repetitively nagging the user for the same URLs.

## Expected Behavior

Denying access should stop the extension from requesting access again.
Perhaps, have a notificaiton symbol in the extension home page that access has been denied and allow the user to accept access at a later date manually to prevent other functions from breaking should that access be essential.

## Specifications

- Chromium: 103.0.5060.114
- TM: 4.16.1
- OS: Win10 Pro

## Script

N/A (all disabled and script updates are disabled because the scripts I used are no longer necessary or non-functional, honestly I should just disable the extension completely at this point)

**Comment by derjanb** [comment]
Have you tried the "Don't ask again" button?

![image](https://user-images.githubusercontent.com/767504/187519394-cc5e55db-5f20-42c0-bbec-572624cb7902.png)

**Comment by AlmostMatt** [comment]
I am experiencing this issue as well. There is no "Don't ask again" button, and the cross-origin requests are caused by tampermonkey despite me turning off all of the settings that I could find related to auto-updating.

Here is an example of a cross origin request permission that comes up roughly once per day:

![tampermonkey spam](https://user-images.githubusercontent.com/3936585/213659654-7a811664-7318-4a57-b251-829e49831d31.png)

I choose "cancel" because I see no reason to allow cross-origin requests, but tampermonkey will keep asking me again on later days. The only extension that I use makes no web requests.

**Comment by derjanb** [comment]
Are you using Chrome's "This can read and change site data" /"Site access" feature?

![image](https://user-images.githubusercontent.com/767504/213661658-82fd97ac-a6f9-476b-bad4-0239cfd454bf.png)


https://github.com/Tampermonkey/tampermonkey/issues/640#issuecomment-462507792

**Comment by AlmostMatt** [comment]
I have that set to "specific sites" since the only extension that I am using affects that specific site (youtube)

![image](https://user-images.githubusercontent.com/3936585/213773135-7b4691bb-016a-402a-ad93-30c5c7285714.png)

**Comment by derjanb** [comment]
@AlmostMatt I thought about this and came to the conclusion that the current behavior is correct.

Tampermonkey is in you case configured to load information from blacklist.tampermonkey.net. 
Therefore the problem is not the request dialog and its repeated appearance but the enabled setting while you obviously want it to be disabled.

So please set "Config mode" to "Advanced" and configure "BlackCheck" > "Userscript Blacklist Source" to "Disabled" or "Manual only".

**Comment by Novivy** [comment]
@derjanb This was working until a few weeks ago and now even tho I have this option disabled, I still get spammed with it about once or twice every 24h or so

**Comment by foinf** [comment]
> @AlmostMatt I thought about this and came to the conclusion that the current behavior is correct.
> 
> Tampermonkey is configured to load information from blacklist.tampermonkey.net. Therefore the problem is not the request dialog and its repeated appearance but the enabled setting while you obviously want it to be disabled.
> 
> So please set "Config mode" to "Advanced" and configure "BlackCheck" > "Userscript Blacklist Source" to "Disabled" or "Manual only".

Doesn't work. I triple checked if I have indeed set this correctly and I still get a new tab opened in my face while I am trying to to something else. If I cancel, I get it again for the same site. Uninstalled the extension for now.

**Comment by derjanb** [comment]
> I still get a new tab

Are you sure it was a Cross Origin Request Check page as show [here](https://github.com/Tampermonkey/tampermonkey/issues/1572#issuecomment-1398119716)?

If so, then an installed script is trying to access a URL... What was the requested match pattern?

**Comment by foinf** [comment]
> > I still get a new tab
> 
> Are you sure it was a Cross Origin Request Check page as show [here](https://github.com/Tampermonkey/tampermonkey/issues/1572#issuecomment-1398119716)?
> 
> If so, then an installed script is trying to access a URL... What was the requested match pattern?

Hi, thanks for responding and sorry for delayed response

I does look like the same thing. Let me attach the screenshot.
![Screenshot 2024-04-20 143050](https://github.com/Tampermonkey/tampermonkey/assets/19815325/1a952e15-6ae3-41ff-a041-dcd63f4b5f01)

And these are my BlackCheck settings:

![Screenshot 2024-04-20 143623](https://github.com/Tampermonkey/tampermonkey/assets/19815325/8b8f9afa-3863-49e6-823d-80d66e51d88c)

I don't fully understand what this is about but my only problem is that hitting cancel does not work as permanent refusal. I don't even use Facebook anymore so I could just disable the script and plugin but it's confusing as to why it keeps popping up again and again.

Thanks again.
