### ISSUE TITLE
@sandbox does not default to "raw" (v4.18.0)

### ISSUE THREAD

**Issue by scholtzm** [Tampermonkey/tampermonkey#1602]
## Expected Behavior
The script that worked in v4.17.x should work without a change in v4.18.0

## Actual Behavior
The script does not work without explicitly specifying `@sandbox raw` in meta

_update:_ It seems to default to "raw" for an already installed script, but not for fresh install.

_update 2:_ `@sandbox raw` needs to be the very first line in meta, otherwise it doesn't work for me.

## Specifications
- Firefox: 105.0.1
- TM: 4.18.0
- OS: Win 10

**Comment by derjanb** [comment]
Can you please reference the script? Does it have a `@inject-into` tag?

> It seems to default to "raw" for an already installed script, but not for fresh install.

The default is always `raw` here. Just double-checked...

> @sandbox raw needs to be the very first line in meta

Shouldn't make a difference, except the script also has a `@inject-into` tag.

> otherwise it doesn't work for me.

What exactly doesn't work in `JavaScript` mode?

**Comment by scholtzm** [comment]
> Can you please reference the script? Does it have a @inject-into tag?

Script sent directly to you. Yes, uses `@inject-into page`, mostly to provide compatibility with Userscripts.app for iOS devices.

> Shouldn't make a difference, except the script also has a @inject-into tag.

Doesn't make sense to me either but if it was not on the first line, it wouldn't work. Might be somehow related to 1602, not sure.

> What exactly doesn't work in JavaScript mode?

The script uses globals from page scope and I can't use `unsafeWindow` because it's not available in Userscripts.

**Comment by ppixiv** [comment]
Was going to file a bug, but I see this is the same problem, so I'll just comment here instead:

My script uses "inject-into page" to tell FireMonkey to inject in page mode, since it defaults to content mode.  This made it behave identically to TamperMonkey.  However, TM 4.18 seems to now interpret "inject-into page" to mean "sandbox JavaScript".  This means that telling FireMonkey to behave like TamperMonkey seems to also tell TamperMonkey to behave something like GreaseMonkey.

Explicitly saying "sandbox raw" doesn't fix it.  It seems like inject-into overrides sandbox.

Two problems I've seen:

- Iterators like URLSearchParams.keys() don't work.  This has never worked for wrapped objects (this is an old Firefox bug), so unsafeWindow.URLSearchParams had to be used instead.  In JavaScript mode, that doesn't work either:

        let params = new unsafeWindow.URLSearchParams("test=1");
        for(let key of params.keys()) console.log(key);

throws "params.keys() is not iterable".  I could work around this, but it means patching a bunch of class prototypes, which is a mess.

- window.dispatchEvent is missing.

Unless I actually run into CSP problems that make this unavoidable I'd much rather stay in "raw" mode, since it's much more compatible across browsers.  This wrapper mode makes Firefox require a lot more browser-specific testing, where in raw mode I see far fewer browser-specific compatibility problems.  (For now I'm probably going to comment out inject-into and see if I can get FireMonkey to fix their default injection mode.  I don't know if that's the only script manager that does that, though.)

**Comment by derjanb** [comment]
> It seems like inject-into overrides sandbox.

You need to add `@sandbox` before to make it work.

> Two problems I've seen:

Thanks for explaining them.

I'll change TM to use `raw` mode for these scripts. However `JavaScript` might become the default in the future because of mv3 restrictions.

**Comment by derjanb** [comment]
Should be fixed at 4.19.6170 (in review|[crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.
