### ISSUE TITLE
Uncaught pagejs missing

### ISSUE THREAD

**Issue by adipiciu** [Tampermonkey/tampermonkey#1617]
(Please fill out the issue template with your details)

## Expected Behavior
No errors should appear.

## Actual Behavior
Starting after the upgrade to Tampermonkey 4.18.0, the error "Uncaught pagejs missing" appears. Scripts are not running. Refreshing the page 4-5 times and sometimes scripts are loading.
Similar to issue https://github.com/Tampermonkey/tampermonkey/issues/1528

Restart browser, restart pc doesn't fix. Violentmonkey works ok.

## Specifications

- Chromium: Chrome 106

## Script
Any script

**Comment by derjanb** [comment]
Can you please backup your scripts and settings, uninstall and re-install Tampermonkey and try again?

Thanks.

**Comment by adipiciu** [comment]
I tried on chromium on Android to uninstall tampermonkey and it works ok after reinstalling it (I had same issue on android)

On Windows, I tried with another method and it seems to work: disable tampermonkey extension, restart browser, enable tampermonkey back. The browser restart is needed. But this way you don't need to reinstall tampermonkey.

**Comment by derjanb** [comment]
Thanks for testing and finding the enabled/disable workaround.

This shows, that this is a bug in Chrome. It does not execute the content scripts in the right order if Tampermonkey was updated from a 4.16.x version. 😔

**Comment by doggy8088** [comment]
> I tried on chromium on Android to uninstall tampermonkey and it works ok after reinstalling it (I had same issue on android)
> 
> On Windows, I tried with another method and it seems to work: disable tampermonkey extension, restart browser, enable tampermonkey back. The browser restart is needed. But this way you don't need to reinstall tampermonkey.

Thanks a lot. Your workaround working perfectly! 👍

1. Disable Tampermonkey extension
2. Restart browser
3. Enable Tampermonkey extension
4. Restart browser

@derjanb How do you know it's a bug in Chrome. Is it possible something changes in Chrome's extension APIs?

**Comment by knakamura8** [comment]
@doggy8088 This worked for me, as well, thanks!  Not sure how this didn't crop up in beta testing =\

**Comment by derjanb** [comment]
> Not sure how this didn't crop up in beta testing =\

A [similar issue](https://github.com/Tampermonkey/tampermonkey/issues/1528#issuecomment-1156120637) was discovered at the BETA version and fixed. Unfortunately it looks like there are more conditions that can cause this issue. Since most of the more than 10 million Tampermonkey users already got the update and there are "only" a few complaints (compared to the overall number of users) the issue seems to happen rarely only.

> How do you know it's a bug in Chrome.

Because it is working after extension re-installation and by using the workaround mentioned above. 
Tampermonkey now uses two content scripts that should be executed in the order they are defined. For some reason this is not always the case when 4.18 is installed over a 4.16 or 4.17  installation. Disabling the extension seems to cleanup things and the content scripts are executed in the right order again.

**Comment by sinsinpub** [comment]
guess not due to chrome change, because i haven't updated my chrome over 1 year (still <100) and kept pc and chrome opened all the time. it either happened here randomly since extension auto updated to recent version (4.18?).

have tried to disable extension, restart chrome, enable again. it works good so far. maybe just the changes of new version make extension update process over old installation break something (content scripts loading order)? so reloading extension once did the cleanup?

**Comment by LatinSuD** [comment]
For me it seems to only break in an old internal web page with a self-signed certificate.
First load usually works fine, but the rest of the times not.

**Comment by derjanb** [comment]
@LatinSuD Do you see the `Uncaught pagejs missing` error at the console?

**Comment by LatinSuD** [comment]
> @LatinSuD Do you see the `Uncaught pagejs missing` error at the console?

Yes.

And then no scripts are run. Tampermonkey icon reports as if there were no scripts for this site (but there should be a few, including some scripts to be run in all sites).

**Comment by derjanb** [comment]
Have you tried to disable Tampermonkey, restart you pc (or browser, but make sure all browser processes are shut down) and reenable Tampermonkey?

https://github.com/Tampermonkey/tampermonkey/issues/1617#issuecomment-1287637401

**Comment by LatinSuD** [comment]
workaround works! thank you!

**Comment by mosquitobird11** [comment]
Workaround does not work for me, I am still getting `Uncaught pagejs missing` randomly on page load even after disabled tampermonkey, a full computer restart, and reenabling. This is issue is very impactful to my daily workflow :(

**Comment by adipiciu** [comment]
> Workaround does not work for me, I am still getting `Uncaught pagejs missing` randomly on page load even after disabled tampermonkey, a full computer restart, and reenabling. This is issue is very impactful to my daily workflow :(

Disable Tampermonkey from Chrome - Extensions, not from the Tampermonkey menu.

**Comment by mosquitobird11** [comment]
@adipiciu for some reason I thought the menu toggle was toggling the extension off somehow, this totally fixed it for me thank you 😄

**Comment by derjanb** [comment]
Shouldn't be an issue anymore...
