### ISSUE TITLE
Forced Chromium Update Breaks Scripts

### ISSUE THREAD

**Issue by knakamura8** [Tampermonkey/tampermonkey#1627]
## Expected Behavior
Not releasing Alpha or Beta Channels into Stable

## Actual Behavior
Releasing Alpha or Beta Channels into Stable

## Specifications
e:  Apologies for the frustration.  Forced extension update for version 4.18.0 breaks loading of many scripts.  Have to refresh pages manually multiple times to get them to properly load.  One can look at the extension page under Chromium here (https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) to see all the complaints (sort by Recent).

How was this update pushed to Stable?  Please issue a forced rollback until 4.18.0 is adequately tested.

**Comment by knakamura8** [comment]
@run-at document-end appears to be the main offender.  Refreshing a page sometimes 5 or 6 times allows scripts using this directive to properly load.  Still unsure how this passed alpha or beta testing.

**Comment by knakamura8** [comment]
#1617 #1615 #1620

**Comment by knakamura8** [comment]
Following suggestion of disabling extension, closing Chromium, re-opening Chromium, then once again re-enabling extension, works.  However, unsure as to why this was not discovered during testing.

**Comment by derjanb** [comment]
> Following suggestion of disabling extension, closing Chromium, re-opening Chromium, then once again re-enabling extension, works.

Closing per https://github.com/Tampermonkey/tampermonkey/issues/1627#issuecomment-1287826705

> However, unsure as to why this was not discovered during testing.

A similar issue was discovered at the BETA version and fixed. Unfortunately it looks like there are more conditions that can cause this issue. Since most of the more than 10 million Tampermonkey users already got the update and there are "only" a few complaints (compared to the overall number of users) the issue seems to happen rarely only.

One question, are you using the BETA version? If that had been the case, the problem might have been discovered sooner. 😉
