### ISSUE TITLE
[Bug]script basic api hook is effect other script

### ISSUE THREAD

**Issue by lihengdao666** [Tampermonkey/tampermonkey#1723]
(Please fill out the issue template with your details)

## Expected Behavior
script basic api is isolate

## Actual Behavior
if String Function is cover，this behavior will effect other script

## Specifications

- Firefox 110.0 (64 bit)
- TM: 4.18.1
- OS:window 11 22H2

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name         Other Script
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.baidu.com/
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        GM_xmlhttpRequest
// @grant        unsafeWindow
// ==/UserScript==

alert(GM_info.script.version.replaceAll('.',''))
```

```js
// ==UserScript==
// @name         String Replace
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.baidu.com/
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        GM_info
// @grant        unsafeWindow
// @run-at       document-start
// ==/UserScript==

String.prototype.replaceAll = function (s1, s2) {
    return 'string is error';
};

```

**Comment by derjanb** [comment]
Yes, that's why monkey patching official functions and APIs is a bad idea. Use [Ponyfills](https://github.com/sindresorhus/ponyfill) instead. ;-) 

In theory it would be possible to have a per-script-context in FF using `// @sandbox JavaScript`, but that would make this environment different than all the others. 
This might change later in MV3 once Chrome supports creating a context per script as well.
