### ISSUE TITLE
Provide a `GM_info.userAgentData` like API to get browser and OS info reliably

### ISSUE THREAD

**Issue by chipzhang** [Tampermonkey/tampermonkey#1728]
`navigator.userAgent` is not reliable since it may be changed by another browser extension.
It seems there is no reliable way to get browser and OS info via TM API.

ViolentMonkey has such an API:
https://violentmonkey.github.io/api/gm/#gm_info

**Comment by derjanb** [comment]
Should be fixed at 4.19.6178 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

I decided to go with `userAgent` because that's what it is.

```ts
export type UserAgentInfo = {
    platform: {
        arch: string, // 'arm' | 'x86-32' | 'x86-64' ...,
        os: string // 'android' | 'linux' | 'mac' | 'win' ...
    },
    browser: {
        name: string, // 'chrome' | 'firefox' ...
        version: string,
        vendor: string
    }
};
```

Chrome/Edge users, please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions`.
Firefox users please install the [BETA version](https://www.tampermonkey.net/index.php?browser=firefox) or check for BETA version updates at `about:addons` 

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by derjanb** [comment]
`userAgentData` is available for testing at 4.19.6179 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|[xpi](https://firefox.tampermonkey.net/firefox-current-beta.xpi))

**Comment by chipzhang** [comment]
@derjanb 

ViolentMonkey first introduces such browser checking API (as well as OS and arch checking).
As per [its doc](https://violentmonkey.github.io/api/gm/#gm_info), its API reads:

- `GM_info.platform.arch`: One of "arm", "mips", "mips64", "x86-32", "x86-64"
- `GM_info.platformbrowserName`: "chrome", "firefox" or whatever was returned by the API.
- `GM_info.platformbrowserVersion`
- `GM_info.platformos`: One of "android", "cros", "linux", "mac", "openbsd", "win".

Are you considering keeping the same GM_info API as ViolentMonkey, thus maximizing the compatibility of user scripts?

**Comment by 7nik** [comment]
It was proposed in [the discussion](https://github.com/Tampermonkey/tampermonkey/discussions/1731) to use the `userAgentData` format.

**Comment by jb222** [comment]
Could someone explain what has changed, with examples, please?
