### ISSUE TITLE
Wrong loading SourceMap of require library

### ISSUE THREAD

**Issue by indefined** [Tampermonkey/tampermonkey#1748]
## Expected Behavior
The browser loading the correct SourceMap and no warning happen

## Actual Behavior
A "failed to load SourceMap" warning happen

## Details
The modern browser will load the SourceMap of the script if a `sourceMappingURL` is specified, but some of script use a relative path for the sourceMappingURL, like this one `//# sourceMappingURL=gif.js.map`
This won't make any problem if the browser load the script via a link, but when Tampermonkey load a `@require` library, it tie the library to the user script together and inject it directly,  This will make the relative path become **relative to the extension path** and result the loading fail.
This problem won't affect most of the user and dev, but the warning does looks annoying, even simply delete the relative source mapping URL is better than leave a warning. The best solution may be redirect the SourceMap to the local file. Make the relative path to a absolute URL also solve the problem, but may probably slowing down the page loading.
I found a related issue #1125 and it's marked as solved in 4.12, but the main report seems not the same problem, the comment did reported a same issue https://github.com/Tampermonkey/tampermonkey/issues/1125#issuecomment-774476127

## Specifications

- Chromium: 109
- TM: 4.18.1 & dev 4.19.6180
- OS: win10

## Script
```js
// ==UserScript==
// @name        test require
// @namespace   testing
// @description 2023/3/26 13:05:08
// @match       *://*/*
// @grant       none
// @require
// @require     https://cdn.staticfile.org/gif.js/0.2.0/gif.js
// @version     1.0
// @author      -
// ==/UserScript==
console.log(GIF)
```

**Comment by 7nik** [comment]
Source maps won't work anyway due to wrapping the script into the sandbox and prepending it with the required scripts. Also, multiple `sourceMappingURL`s will conflict.

Stripping it out may also be a bad idea because vite-plugin-monkey [can ship](https://github.com/violentmonkey/violentmonkey/issues/1616#issuecomment-1279976848) a correct source map which takes into account [the shifting](https://github.com/Tampermonkey/tampermonkey/issues/1621#issuecomment-1280239828).
