### ISSUE TITLE
New script update tab even when "show TM update notification" is disabled and "don't ask me for simple script updates" is enabled and a new chrome profile is used

### ISSUE THREAD

**Issue by nomino3390** [Tampermonkey/tampermonkey#1753]
## Specifications

- Chromium: Windows 10 chrome Version 111.0.5563.147 (Official Build) (64-bit)
- TM: 4.18.1
- OS: Windows 10 64 bit Version 10.0.19044 Build 19044

## Script: https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/userscript/bpc.en.user.js

This isn't closed and isn't solved in issue 427 or any of many other mentions of this issue. Users keep posting about this because it's still an issue.

![tampermonkey update notification disabled](https://user-images.githubusercontent.com/129557820/229242089-97677f2a-e176-4848-a2fc-1967e966d2a8.PNG)
![tampermonkey script settings](https://user-images.githubusercontent.com/129557820/229242091-359dfe88-60f0-4c1a-a697-473a7e539a9d.PNG)
![tm auto script updates](https://user-images.githubusercontent.com/129557820/229242092-158dc850-699d-4549-a545-79c8d972f4c0.PNG)
![1](https://user-images.githubusercontent.com/129557820/229242093-5ca5b6ff-dca3-4e30-9cab-4979b0b6de23.png)

**Comment by 7nik** [comment]
#427 is about opening the changelog after TM update and isn't related to the userscripts update.

Regarding the linked userscript: its author adds and removes `@match` almost every month. And this is an important change because you may want or do not want to run the script on the added/removed site(s). Also, this is related to security because you likely don't want the userscript run on your bank's site or something.

**Comment by nomino3390** [comment]
> #427 is about opening the changelog after TM update and isn't related to the userscripts update.
> 
Got it. Well it's part of the same problem, opening a new tab due to updates, without the user requesting so, regardless of settings selected, even if those settings aren't intended to prevent the spam.

> Regarding the linked userscript: its author adds and removes `@match` almost every month. And this is an important change because you may want or do not want to run the script on the added/removed site(s). Also, this is related to security because you likely don't want the userscript run on your bank's site or something.

Why should TM bug the user every time you want to use a script on new website, without an option to successfully disable the notification, when almost all chrome extensions don't?

**Comment by derjanb** [comment]
You don't want to disable the notification, but the automatic script update (`Check Interval` set to `Never`). After this you can trigger manual updates.

**Comment by derjanb** [comment]
@MaverickMartyn Simply have a look at the post above yours to see how to disable automatic script updates. 🤷

**Comment by MaverickMartyn** [comment]
That doesn't solve the problem.
I want updates, I just don't want to be notified of them.

**Comment by SuperFurias** [comment]
Users should be free to have an option to disable this shit. its simple.
Even if its an update that can allow the userscript to "run on your bank's site"
You should have an option to disable the update popup.
Because, realistically speaking, most people don't really read the changes when the popup update shows up.
or at least, if i trust someone's script, when the update popup shows up, i just randomly click "update" without reading nothing.
i know its unsafe. but who cares.
