### ISSUE TITLE
Can editor Linter false positive issues be fixed?

### ISSUE THREAD

**Issue by dnknn** [Tampermonkey/tampermonkey#1853]
![239_19230122](https://github.com/Tampermonkey/tampermonkey/assets/10995302/a212f2f2-18c2-4c5e-9918-d2c8e84ab4a6)

> [Comma operator `(,)` | MDN⤤](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator)　

```js
return	(111,	222)               // no problem

const log = (...g)=> (111,	222)  // Warning!, because the syntax is correct, I don’t want the warning to appear.
```

**Comment by derjanb** [comment]
@dnknn Please disable this rule via comment or create an own ESLint config based on [Tampermonkey's config](https://github.com/Tampermonkey/tampermonkey/issues/1686#issuecomment-1403657330).

**Comment by dnknn** [comment]
@7nik @derjanb Thank you very much for the enthusiastic reply!

Then I would like to ask you how to use it, because I know nothing about [ESLint⤤](https://eslint.org/docs/latest/use/configure/).

Can you explain the process in a little more detail (it would be better if have screenshots :)), thanks again

**Comment by 7nik** [comment]
The rule is generally triggered because you either made a mistake or wrote code in a bad style.
`const log = ()=> (111,	222)` and `const log = () => 222` are absolute equivalent. But it's an example and, I'm sure, in your code it makes sense, so it's probably a bad style.

I proposed to use control comments to configure ESLint behaviour. Just paste them before the problem lines or at the script beginning.

derjanb proposed to configure ESLint for all your scripts: go to the TM Settings, change Config mode to Advanced, go to the Editor section and paste to the Custom Linter Config field [this default config](https://github.com/Tampermonkey/tampermonkey/issues/1686#issuecomment-1403657330), then add there to the `rules` `"no-sequences": 0` (and comma where need) to disable the rule no-sequences.

**Comment by dnknn** [comment]
ThankYouVeryMuch! I pasted `{"no-sequences": 0}` separately, it didn’t work, It only works if paste them all.

> `const log = ()=> (111, 222)` and `const log = () => 222` are absolute equivalent.

- No, not absolutely equal, in addition to getting the `return value`. 
	> Before returning the return value, do some auxiliary operations, for example:
```js
[...document.querySelectorAll`li.xx`].map(ee=> (ee.classList.add`done`, ee.textContent) )
```
```js
[...document.querySelectorAll`li.xx`].map(ee=> {
	ee.classList.add`done`;
	return	ee.textContent;
} )
```

**Comment by 7nik** [comment]
> But it's an example and, I'm sure, in your code it makes sense

> so it's probably a bad style

yeah, it is

good style would be something like this
```js
for (const elem of document.querySelectorAll("li.xx")) {
  elem.classList.add("done");
  const text = elem.textContent;
  // whatever you do after map()
}
```
though it may turn into something else depending on what are you doing after `map()` and other surrounding code
