### ISSUE TITLE
White screen instead of configuration on Sonoma

### ISSUE THREAD

**Issue by numo68** [Tampermonkey/tampermonkey#1893]
## Expected Behavior

The extension can be configured and works

## Actual Behavior

Clicking on the TM icon gives rotating green/blue circles for about 15 seconds and nothing happens.

Trying to open the TamperMonkey App, then clicking Open in Safari opens the ui.tampermonkey.net/options.html, renders however just a blank white page.

Tried disabling every other extension (I have AdGuard), did not help. Tried uninstalling/reinstalling, does not help. After browsing through issues tried allowing unsigned extensions, did not help. Tried killing everything TM-related in Activity Monitor, did not help.

There are some errors in the console but I am unfortunately not a web developer to make sense of them:

![Image 11-11-2023 at 20 11](https://github.com/Tampermonkey/tampermonkey/assets/5095188/8871b5b8-1b89-4659-9fb0-62061675f01c)

Thanks for a good software anyway, I am using it on Windows machines and there it works flawlessly, so I hope this will be fixed as well.

## Specifications

- Browser: Safari 17.1
- TM: 4.20.6188
- OS: macOS Sonoma 14.1.1
- Hardware: MacBook Air M2 (a few days old, basically initial setup from scratch)

## Script

... did not get so far

**Comment by numo68** [comment]
> I've had the same problem, and found a solution by accident: in Safari settings (`<⌘-,>`), under "Extensions", "Tampermonkey", "Permissions", I clicked "Always Allow on Every Website...". Afterwards Tampermonkey started to work.

Confirm that this is working. Thanks!

**Comment by mgax** [comment]
I think the ticket is still valuable. Tampermonkey should provide some indication to the user of what they should do. It took me quite a bit of time trying random things until this worked.

**Comment by derjanb** [comment]
The page should already ask to enable the extension for every site. Isn't it?

[
![image](https://github.com/Tampermonkey/tampermonkey/assets/767504/7f6b41d5-b7ba-460c-8fdb-47d1a7f0d924)
](https://ui.tampermonkey.net/safari_extension_enable.jpg)

**Comment by derjanb** [comment]
> But I don't remember Tampermonkey asking.

Tampermonkey "asks" as shown at the image above, which is visible if it has no access to the page.

> Out of curiosity, what is the reason for that requirement? To be fair I'd really prefer to have the browser to (also) decide which pages the extension is allowed to operate on.

Of course. This is a new feature in Safari that was not there/enabled by default earlier. Most probably I have to adapt by explicitly adding `ui.tampermonkey.net` to the required host permissions.

**Comment by cbrunnkvist** [comment]
It does seem very glitchy. I restarted Safari a couple of times to make sure that it wasn't a lifecycle issue, but I was only getting the spinner and then white box after I first installed the extension and set _Always Allow For This Site_ where I needed it. 

Now, after switching to Allow on ALL, it worked. I then switched permission _back_ to "Deny on other + allow only configured"... and now it seems to be working as expected?!

Perhaps something about the first launch, prior to any configuration is written etc?

**Comment by Artiomtb** [comment]
"subscribing to updates"

**Comment by phantomsoul1** [comment]
There are 2 parts to this, both of which are the result of policy changes in Safari 17, that ships with Mac OS Sonoma:

1. The Tampermonkey extension must be allowed to run against the ui.tampermonkey.net domain. For some reason, Safari does not prompt to allow this if your permission level to all websites is "Ask" - my guess is that the extension is supposed to declare mandatory domain(s) that are to be trusted for the basic execution of the extension. It seems like as of Safari v17.1, Tampermonkey.net and ui.tampermonkey.net are no longer considered interchangeable domains.
2. In order for the extension widget menu to work, the script must be allowed to run against the domain of the page that is currently loaded. Here, you should see the prompt if the page's domain permission for Tampermonkey resolves to "Ask." In order to see the menu, the loaded page's domain must be allowed, even if just for a day (as the prompt offers). This makes sense, as Tampermonkey itself should only be allowed to run while browsing domains that you expect to use it with and not any others.

Once I do these things, the menu and UI pages load successfully, when browsing sites that I expect to use scripts with. I have my global permission for Tampermonkey set to "Ask," so all other sites will prompt me to allow Tampermonkey to run with their domain, which I can either grant for day, if expected, or simply not grant if not expected. "Deny" for a global setting can work too, particularly if other people use the computer, who may not understand what the prompt means if it comes up; in that case, you just have to remember to check for access errors and adjust these permissions as needed Tampermonkey doesn't load right for a new site it is expected to be used with.

**Comment by derjanb** [comment]
Fixed in 5.2.6199
