### ISSUE TITLE
CSP failure on lichess.org in Firefox with some scripts

### ISSUE THREAD

**Issue by lainverse** [Tampermonkey/tampermonkey#1934]
## Expected Behavior

On first open site opens and works fine.

## Actual Behavior

On first open site broken and doesn't show many UI elements.
Multiple errors in console starting with two:
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).  [content.js:58:456](moz-extension://dfcc45aa-f49c-4bb1-8879-dae819ee942b/content.js)

Note: Linked test-script below require Instant injection mode for normal operation. With default injection mode this problem reproduce on every subsequent page reload.

## Specifications

- Firefox: 120.0.1 (64-bit)
- TM: 5.0.0
- OS: Windows 10

## Script

Example script: https://greasyfork.org/uk/scripts/19993-ru-adlist-js-fixes
As I understand script runs, but without unsafeMode and since my injections overwrite many default API on the page they all end up unavailable to the page code.

Another example which only breaks WebSocket there and trigger same SCP bug:
```
// ==UserScript==
// @name         Test Script
// @namespace    http://tampermonkey.net/
// @version      2023-12-11
// @description  try to take over the world!
// @author       You
// @match        https://lichess.org/
// @icon         https://www.google.com/s2/favicons?sz=64&domain=lichess.org
// @grant        unsafeWindow
// @grant        window.close
// @run-at       document-start
// ==/UserScript==

(function() {
    'use strict';

    // Your code here...
    const root = unsafeWindow || window;
    root.WebSocket = exportFunction(new Proxy(root.WebSocket, {
        construct(ws, args) {
            console.log(args);
            return Reflect.construct(ws, args);
        }
    }));
})();
```

**Comment by derjanb** [comment]
`exportFunction` get two arguments. The script is working fine that way:

```
    root.WebSocket = exportFunction(new Proxy(root.WebSocket, {
        construct(ws, args) {
            console.log(args);
            return _construct(ws, args);
        }
    }), unsafeWindow);
```

**Comment by lainverse** [comment]
> `exportFunction` get two arguments. The script is working fine that way:
> 
> ```
>     root.WebSocket = exportFunction(new Proxy(root.WebSocket, {
>         construct(ws, args) {
>             console.log(args);
>             return _construct(ws, args);
>         }
>     }), unsafeWindow);
> ```

Not only didn't this improve anything, but it actually broke the page on the first open in the same way as the large script does. Note: If you run the script with instant injection mode enabled, subsequent page reloads work fine with or without specifying a second argument.

I forgot to specify that _construct is actually Reflect.construct, but it doesn't really matter, I suppose.

**Comment by derjanb** [comment]
> Not only didn't this improve anything,

Before it throwed "Error: An unexpected apiScript error occurred", which made the script not working at all.

Unfortunately scripts have to deal with Mozillas Xray Vision because CSP relaxing is unwelcome behavior.

This should work:
```
// ==UserScript==
// @name         Test Script
// @namespace    http://tampermonkey.net/
// @version      2023-12-11
// @description  try to take over the world!
// @author       You
// @match        https://lichess.org/
// @match        *://example.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=lichess.org
// @grant        unsafeWindow
// @grant        window.close
// @run-at       document-start
// @sandbox      JavaScript
// ==/UserScript==

(function() {
    'use strict';

    const root = unsafeWindow || window;
    const ws = root.WebSocket;
    const clone = (x, t = root) => cloneInto(x, t, { cloneFunctions: true });

    const P = unsafeWindow.Proxy;
    const p = new P(ws, clone({
        construct(ws, args) {
            console.log(args);
            return new ws(args);
        },
        get: exportFunction((that, prop) => {
            console.warn('get', that, prop, that[prop]);
            return that[prop];
        }, unsafeWindow),
        getPrototypeOf(target) {
            console.warn('getPrototypeOf', that, prop)
            return ws.prototype;
        }
    }));

    console.log(p.sdf);
    console.log(p.prototype);

    root.WebSocket = p;
})();
```

**Comment by lainverse** [comment]
@derjanb No, at least for me, it doesn't. On the first page opening, it fails. On subsequent page refreshes, it works.

BTW, both scripts work just fine in ViolentMonkey with no CSP errors neither on first open, nor on subsequent reloads.

**Comment by derjanb** [comment]
> On the first page opening, it fails

I can't reproduce this. My script version works here when navigating a tab to the URL, on reloads and even starting FF with "Open previous windows and tabs" enabled. What does "first page opening" mean?

BTW: I don't now why Xray Vision acts different depending on when the code runs.

> I don't even need to set injection mode there. It just works as is. 

Setting "Content Script API" to "UserScripts API Dynamic" will help. Maybe they use something like this. However, in "UserScripts API Dynamic" mode there is a ~1% chance that script injection is not working, because FF somehow doesn't call any webRequest listener, but onResponseStarted, which can't be used to delay the request and setup dynamic injection.

**Comment by derjanb** [comment]
> I've attached a video last time

Sorry. missed that one. 🙈

>  if you don't believe me.

I always believe bug reports, because I see no reason to report something that is not happening. 😉
However, sometimes I need to reproduce things to know what's going on...

**Comment by lainverse** [comment]
Understandable. BTW, I've tried to disable all the other extensions, but the result didn't change.

**Comment by derjanb** [comment]
Takeaways for now:

I don't know why (the real and not stubbed dummy) exportFunction throws without a second argument only if called later than `document-start`.

Further findings:

The pages adds a meta CSP directive after document-start that makes injection impossible. That's why all methods that inject on document-start work. TM 4.19 can't fallback to js (`@sandbox JavaScript`) mode automatically and fails (without Instant Injection).
5.0.0 can fallback to js mode and injects the script, but this "after document-start" injection affects Xray Vision and `exportFunction` then exports the WebSocket class without `prototype` property into the page.

Unresolved is still why you can't get the script [3] to work on the first page load. And I have no idea why this is failing for you. I can't reproduce it.

| GM_info.sandboxMode                                                          | 4.19.0       | 4.19.0 + Instant Injection | 5.0.0 | 5.0.0 + Instant Injection | 5.0.0 + "UserScripts API Dynamic"
| ---------------------------------------------------------------------------- | ------------ | -------------------------- | ----- | ------------------------- | --------------------------------- 
Original script [1]                                                            | not injected | raw                        | js*   | raw                       | raw
Original script with exportFunction and `unsafeWindow` as second argument [2]  | not injected | raw                        | js**  | raw                       | raw
My script that uses `unsafeWindow.Proxy` [3]                                   | not injected | raw                        | js    | raw                       | raw

\*   Tampermonkey throws "An unexpected apiScript error occurred" when `exportFunction` is called
\*\* The page throws "WebSocket.prototype is undefined"


[1] https://github.com/Tampermonkey/tampermonkey/issues/1934#issue-2034620047
[2]

```
// ==UserScript==
// @name         Test Script
// @namespace    http://tampermonkey.net/
// @version      2023-12-11
// @description  try to take over the world!
// @author       You
// @match        https://lichess.org/
// @icon         https://www.google.com/s2/favicons?sz=64&domain=lichess.org
// @grant        unsafeWindow
// @grant        window.close
// @run-at       document-start
// ==/UserScript==

(function() {
    'use strict';
    console.log('TS', GM_info.sandboxMode);
    // Your code here...
    const root = unsafeWindow || window;
    root.WebSocket = exportFunction(new Proxy(root.WebSocket, {
        construct(ws, args) {
            console.log(args);
            return Reflect.construct(ws, args);
        }
    }), unsafeWindow);
})();
```

[3] https://github.com/Tampermonkey/tampermonkey/issues/1934#issuecomment-1854212278

**Comment by lainverse** [comment]
Wait, it seems like the third option actually works. It seems like I reproduced it wrong on my side. I didn't copy it, but I modified my code and didn't notice you used unsafeWindow.Proxy. There's still a CSP error, but the script works.

The only issue with this, I suppose, is that instant injection mode isn't as instant as it has to be. -_-
When code starts only after `document-start` it defeats the whole purpose of instant injection, from my point of view.

**Comment by derjanb** [comment]
>  is that instant injection mode isn't as instant as it has to be.

Do you see issues in Instant Injection mode?

**Comment by lainverse** [comment]
Yes, that's actually why it affects the script only on first open in my case.
When instant injection is disabled that CSP error appears on every subsequent page reload.

**Comment by lainverse** [comment]
![image](https://github.com/Tampermonkey/tampermonkey/assets/4563325/03cb5153-69e2-4c79-b41b-971d7ed0ebe6)
Your version of the script works, though. It just shows a CSP error message.

**Comment by derjanb** [comment]
Now I can reproduce it! 😂 I'll investigate.

"UserScripts API Dynamic" works fine in all cases.

**Comment by derjanb** [comment]
>  It just shows a CSP error message.

Yes, this is because the meta CSP tag is added and Tampermonkey assumed that it can inject script tags.

**Comment by derjanb** [comment]
Finally conclusions:

* First load on 4.19.0 + Instant Injection doesn't work either
* the HTML includes a meta CSP tag and once the HTML is parsed (document.body != null) the new CSP applies
* on first loads the document is parsed while the synchronous XHR of Instant Injecton retrieves the script data, the injection then still happens before any page scripts, but after the DOM is parsed
* in UserScripts API Dynamic mode the script data is there earlier so that the DOM always is parsed after scripts are injected

So either use `unsafeWindow.Proxy` to be prepared for `@sandbox JavaScript` environments or ask the script users to switch to "UserScripts API Dynamic" mode.

**Comment by lainverse** [comment]
@derjanb I went with unsafeWindow.Proxy and cloneInto for now. I've tried "UserScripts API Dynamic" mode, but it still shows a CSP error in console and things break (w/o unsafeWindow.Proxy and cloneInto).

**Comment by derjanb** [comment]
>  I went with unsafeWindow.Proxy and cloneInto for now

👍

> but it still shows a CSP error in console

You have to press the "Save" button at the end of this section after "UserScripts API Dynamic" was selected. Then no CSP error should appear.

**Comment by lainverse** [comment]
Huh, didn't expect that to require a "Save" button. Thought it's only necessary to save editable fields like whitelist and blacklist in that section.

**Comment by derjanb** [comment]
Yeah, this is something I'd like to improve. Sections that have text areas have a save button and others don't.

The plan is to rewrite the UI from scratch, it is based on code it from 2010 at many parts, but for now the migration to MV3 and iOS support are more important.
