### ISSUE TITLE
TM is not loading on my browser

### ISSUE THREAD

**Issue by agusnieves** [Tampermonkey/tampermonkey#2028]
(Please fill out the issue template with your details)

## Expected Behavior
TM to load correctly

## Actual Behavior
TM seems not to be loading in Chrome, the icon is greyed out and once I click it, it loads for a while and displays the message "_An internal error occurred. If the problem persists even after a restart of the browser, please press OK and report this issue at the forum._"

And that is what I am doing after restarting the browser several times. It was working perfectly before April 3rd. 

## Specifications

- Chrome: 123.0.6312.106
- TM: 5.1.0
- OS: Windows 11 Pro 22631.3296

## Script

N/A

**Comment by derjanb** [comment]
Can you please check the background page for errors?

https://tmnk.net/faq#Q600

**Comment by Milburne** [comment]
I have experienced this same issue. Trying to start TM I get the whirlygig for several seconds and then the dialog the OP describes. I did click on the link for the background code links which brings up the DevTools window where I see an error in the Console section:
`Uncaught (in promise) Error: Error listing values.
    at n.onerror (background.js:385:464)`
Is this an error in the script? Since TM is not loading I cannot get to the built-in editor to see it. Thanks.
OS: Linux Mint: Linux version 5.4.0-176-generic (buildd@bos03-amd64-046) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2))
Browser Slimjet - 42.0.3.0 (based on Chromium 120.0.6099.18) (Official Build) (64-bit)

**Comment by derjanb** [comment]
> Is this an error in the script? 

No. Tampermonkey is loading data from a database when it starts. And this is failing. Can you please try to reinstall Tampermonkey? If you have important scripts installed, then please create a backup of your profile folder first.

**Comment by Milburne** [comment]
Thank-you Jan. De-installing and re-installing then re-adding my script corrected the issue as you suggested.
