### ISSUE TITLE
Tampermonkey suddenly stopped working.

### ISSUE THREAD

**Issue by DeltaStruct** [Tampermonkey/tampermonkey#2137]
Tampermonkey suddenly stopped working.
I also tried disabling Tampermonkey and restarting the browser, but nothing changed.
I would like to see a list of user scripts installed if they are difficult to recover.

## Actual Behavior
All script not working.
When I open options.html, it says that an internal error has occurred.
![image](https://github.com/user-attachments/assets/eb3082e9-bbcd-4078-b296-4e77a32de6ba)
## Specifications
- Google Chrome: 127.0.6533.72
- TM: (i.e. 4.5.5648) idk what this is sorry...
- OS: Debian 12.6 (KDE Plasma 5.27.5)
## Script
(Please give an example of the script if applicable.)

**Comment by derjanb** [comment]
Please open the developer tools. Does the console tab show any errors?

**Comment by DeltaStruct** [comment]
No errors were shown.
![image](https://github.com/user-attachments/assets/3bcafcad-0790-4fda-94d1-4c53b018e4e7)

**Comment by DeltaStruct** [comment]
Sorry, I closed it by mistake.

**Comment by derjanb** [comment]
Ok, then please open a tab and paste this URL: `chrome://extensions/?id=dhdgffkkebhmkfjojejmpbldmpobfkfo`. Find the "service worker" entry at "Inspect views" and click it. Do you see errors at this console tab?

**Comment by DeltaStruct** [comment]
In "Inspect views" only background.html was found. There I see an error.
![image](https://github.com/user-attachments/assets/0c16482d-8448-44bb-a460-96637a6dc60b)

**Comment by derjanb** [comment]
The first issue is that [`chrome.storage.session`](https://issues.chromium.org/issues/344767727) is not available even though it should. The next issues is that probably the indexedDB in the browser profile folder is broken.

Can you please try a new temporary profile?

**Comment by DeltaStruct** [comment]
I tried it with a new profile and it worked.
![image](https://github.com/user-attachments/assets/57e65fe0-5820-41ab-8b8b-33ab77ddb66d)
"Service Worker" also exists.
![image](https://github.com/user-attachments/assets/68b801fa-e7bb-46ed-8fe7-4f0024df46b7)

**Comment by zpiao119** [comment]
我在win10使用Chrome也是同样的问题

**Comment by FabriceNeyret** [comment]
Same here: suddenly stop working on Chrome while working in FF.
Error messages relate to fonts violating Content Security Policy: (I don't even know it was possible :-O ) : 

Refused to load the font 'data:font/truetype;charset=utf-8;base64,d09GRgABAAAAALY3ABIAAAABztAAAAAAAAC1QAAAAPcAAAHiAAAAAAAAAABHUE9TAACV9AAAFxIAAHKy/pn970dTVUIAAK0IAAAINQAAFD6g2KReTFRTSAAABtQAAAA6AAACQeO3nq5PUy8yAAACDAAAAFMAAABgZoZye2NtYXAAABxsAAADdwAABTpa8HPyY3Z0IAAAIbAAAAAoAAAAKAhGAbdmcGdtAAAf5AAAAQUAAAFzBpmcN2dhc3AAAJXoAAAADAAAAAwABwAHZ2x5ZgAAJkQAAGT0AADhaCjCChFoZG14AAAHEAAAFVwAADPIhU9AOGhlYWQAAAGUAAAANQAAADYFph12aGhlYQAAAcwAAAAgAAAAJAc2BPtobXR4AAACYAAABHEAAAj0jIVtDGxvY2EAACHYAAAEbAAABHyCc7p8bWF4cAAAAewAAAAgAAAAIARXAjxuYW1lAACLOAA...SCThVMYJIqZCqSu4rDezyzyKpY17tqhUyLsX30L+SQltAyggVZVqVMsLfPk1CNKvWoXtPreoMd2Ymd2YVd2S2+tbRTX92te3Sv7tP9egCjlnZ0oid96c/8LMkyrMgarMP67MDvNkYxV0uGjvOJFo+33umRlTnS48NR0ehv5tf6D/25M7IAAAB4AYVRRXfDMAz+K3q+jBc4DVyPmfGu56iNk9bKc9QO/ny5Y7iJP5DukGCGgtCjUDv2DZWsxsroHvmMA3jsUEM9TnoQx8NmHEMax+sKuqHdULlItRFFljsdCtZhW14qWh2mCiKj286Srwlc9vMROJ8M/Hcsak/njBZ6FrPHXtAKON/k7e/j0OQAb9h+mHVQhtg6Gm/r2TmjLVcvwbVymR6e31sY89p7uwn3o6Nvmx8XAmbUwVBOd48CVrkrwdWA8NYEbn69Ft3Z/AmDvFqGE2/fj78tvTlH0w9MfcpAGK7ZliRjjd2agD20SKpx8c34aPZXMwDpj6h5' because it violates the following Content Security Policy directive: "font-src github.githubassets.com".

/Tampermonkey/tampermonkey/issues:187 Refused to load the font 'data:font/truetype;charset=utf-8;base64, d09GRgABAAAAALM7AA8AAAABq0AAAAAAAACyRAAAAPcAAAHiAAAAAAAAAABHUE9TAACIDAAAIgQAAH82Ol56cUdTVUIAAKoQAAAIMwAAFD6gNKPBT1MvMgAAAdAAAABVAAAAYGbqc4pjbWFwAAAGbAAAA3wAAAU4Vch3gWN2dCAAAAwYAAAAQAAAAEAQPwNiZnBnbQAACegAAAEDAAABcwZZnDdnbHlmAAAQvAAAbJ4AAOZUwSn/MmhlYWQAAAFYAAAANgAAADYGApswaGhlYQAAAZAAAAAgAAAAJAdbBRtobXR4AAACKAAABEIAAAjwrN1ggGxvY2EAAAxYAAAEYgAABHqHyk9obWF4cAAAAbAAAAAgAAAAIARWA2ZuYW1lAAB9XAAAAoEAAAZuOd88j3Bvc3QAAH/gAAAIKgAAEi5ynk2NcHJlcAAACuwAAAEqAAACpAoaNTMAAQAAAAEAAA...STdLpgIn7fZCqSu5rDezyzyKpZz7vqhExLsEP0L+KQltJygoVYTqVM+PxDJaFaVekJvaE39RY7sTO7sCu7sbtQL3VQf92n+/WAHtRDehiopT2d6UU/BrAAS7EsK7Em67IBO/KnjVXM1dKhE3yixfOtb3pmZY70/HBUmjxmflv/BTgtM3AAeAGFUUV3wzAM/it6vowXOA1cj5nxrueojZPWynPUDv58uWO4iT+Q7pBghoLQo1A79g2VrMbK6B75jAN47FBDPU56EMfDZhxDGsfrCrqh3VC5SLURRZY7HQrWYVteKlodpgoio9vOkq8JXPbzETifDPx3LGpP54wWehazx17QCjjf5O3v49DkAG/Yfph1UIbYOhpv69k5oy1XL8G1cpkent9bGPPae7sJ96Ojb5sfFwJm1MFQTnePAla5K8HVgPDWBG5+vRbd2fwJg7xahhNv34+/Lb05R9MPTH3KQBiu2ZYkY43dmoA9tEiqcfHN+Gj2VzMA6Y+oeQ==' because it violates the following Content Security Policy directive: "font-src github.githubassets.com".
(twice)

**Comment by axel-magard** [comment]
Same here: stopped working in Google Chrome. Userscript is not shown anymore as active for a given url. Works with Firefox. I tried w/o success:

- new google chrome profile
- switching extensions to developer mode ( as mentioned [here ](https://www.tampermonkey.net/changelog.php?locale=en&more=true&show=gcal))

**Comment by homes410** [comment]
Here's workaround for those who are witnessing this problem, Start Chrome with --disable-renderer-backgrounding appended to its command argument. Any extension process of Chrome is started as lowest priority so if you have high-load tabs, Tampermonkey extension would become sluggish, for now this is only way.

**Comment by EricE549X** [comment]
> Ok, then please open a tab and paste this URL: `chrome://extensions/?id=dhdgffkkebhmkfjojejmpbldmpobfkfo`. Find the "service worker" entry at "Inspect views" and click it. Do you see errors at this console tab?

is there an equivalent to this for safari? i've been having issues every tuesday for over a month now

**Comment by komatosse** [comment]
> Here's workaround for those who are witnessing this problem, Start Chrome with --disable-renderer-backgrounding appended to its command argument. Any extension process of Chrome is started as lowest priority so if you have high-load tabs, Tampermonkey extension would become sluggish, for now this is only way.

This didn't work for me ;/ Did anyone find the solution?
My scripts stopped working altogether, even though they show as active on the pages they should be. I tried reinstalling Tampermonkey, but no luck fixing the issue

**Comment by derjanb** [comment]
> Under Extensions I get told that Tampermonkey ( among others ) is an extension possibly not supported anymore.

@axel-magard Please to to `chrome://extensions`, enable developer mode and press the update button at the upper left.

> Error messages relate to fonts violating Content Security Policy

@FabriceNeyret This errors are not related to any Tampermonkey issue.

> is there an equivalent to this for safari? i've been having issues every tuesday for over a month now

@EricE549X Please check #2153

> My scripts stopped working altogether, even though they show as active on the pages they should be.

@komatosse 

Please open a tab and paste this URL: chrome://extensions/?id=dhdgffkkebhmkfjojejmpbldmpobfkfo. Find the "service worker" entry at "Inspect views" and click it. Do you see errors at this console tab?

**Comment by rcchan** [comment]
Same issue for me. Mine was related to #2011 and temporarily re-enabling via chrome://flags/#mutation-events makes the scripts work again

**Comment by punnerud** [comment]
I had the same issue, uninstalled (**copy all scripts first because they will be lost**) and reinstall. Now it works again.

**Comment by vbtueli** [comment]
> Here's workaround for those who are witnessing this problem, Start Chrome with --disable-renderer-backgrounding appended to its command argument. 

this worked for me, i was bothered for a long time, thanks.

**Comment by derjanb** [comment]
The reporter's issue should be fixed now. Closing.

**Comment by Pikamander2** [comment]
@derjanb - This doesn't appear to be resolved. My scripts stopped working today and I had to enable the chrome://flags/#mutation-events flag for them to start working again. Is there a permanent fix planned?

**Comment by harking** [comment]
@derjanb can we reopen this. Same situation here, all scripts stopped working. Needed to enable mutation-events to get things working again

**Comment by derjanb** [comment]
What is your Tampermonkey version?

**Comment by harking** [comment]
I'm not utilizing any mutation events. I'm on TamperMonkey 5.3.3. None of my tamper monkey scripts are not loading unless i enable mutation-events

**Comment by harking** [comment]
After restarting the browser and disabling mutation events again (set to default), Tamper monkey seems to be working again without mutation events enabled. ¯\_(ツ)_/¯

**Comment by Pikamander2** [comment]
> After restarting the browser and disabling mutation events again (set to default), Tamper monkey seems to be working again without mutation events enabled. ¯_(ツ)_/¯

I had this exact same experience. Turning the mutation events back on fixed my scripts, but then they still worked after turning the mutation events back off.

Although, just a word of warning, my scripts got corrupted this morning and all disappeared from Tampermonkey, so I had to restore them from backups. It might be completely unrelated, but go back your scripts up now just in case.

**Comment by derjanb** [comment]
> Enabling the #mutation-events flag and disabling fixed it.

I can't imaging why this should help, except that you have to restart Chrome because of the flag modification.
So restarting Chrome (be sure that every process is closed) should have the same effect.
