### ISSUE TITLE
Outdated sources

### ISSUE THREAD

**Issue by devnoname120** [Tampermonkey/tampermonkey#214]
Would it be possible to update the repository with the latest sources?
It would allow people to contribute.

Thank you!

**Comment by omarjackman** [comment]
:+1:

**Comment by yuvilio** [comment]
Echoing this. Looking at this repo and seeing the main branches not updated since 2013 makes this feel like an abandoned project, though it's clearly not from it's releases.

**Comment by Chaz6** [comment]
Hi derjanb, you closed my ticket, so any news on this issue? Thanks!

**Comment by alexlur** [comment]
@Chaz6 I unzipped the crx file and the LICENSE file says 

> Copyright 2015 Jan Biniok. All rights reserved.

So I guess it has now become a closed source software.

**Comment by derjanb** [comment]
Closed via e547f53

**Comment by devnoname120** [comment]
@derjanb If you don't mind, could you please explain your decision to close the source of this project? Have you had any negative experience? Thank you.

**Comment by asl97** [comment]
The final release was at the start of 2013 so those post should be relevant (at least the second link).
https://forum.tampermonkey.net/viewtopic.php?t=81#p712
https://forum.tampermonkey.net/viewtopic.php?t=858#p3198

**Comment by TomasHubelbauer** [comment]
FWIW the posts have been deleted, or rather it looks like the entire forum was. I tried using the Wayback Machine but I couldn't find any hits for either of the links. That seems surprising. I did not find a forum link on the TamperMonkey webpage so I think the forum was just closed and either the posts were super short-lived before that happened or they were scrubbed from Wayback Machine. I did not try any other place that would mention the motivation for going closed-source and still be readable today, unfortunately. There is https://github.com/Tampermonkey/tampermonkey/issues/1515 but the reasons for the decision are not explained there, only assurances about the continued privacy and security of the extension (which I do find credible but am still curious as though why the change was made).

**Comment by asl97** [comment]
> FWIW the posts have been deleted, or rather it looks like the entire forum was. I tried using the Wayback Machine but I couldn't find any hits for either of the links. That seems surprising. I did not find a forum link on the TamperMonkey webpage so I think the forum was just closed and either the posts were super short-lived before that happened or they were scrubbed from Wayback Machine.
> 
> I did not find any other place that would mention the motivation for going closed-source and still be readable today, unfortunately. There is #1515 but the reasons for the decision are not explained there, only assurances about the continued privacy and security of the extension (which I do find credible but am still curious as though why the change was made).

That forum post should have existed some time after 2013 to at least 2017

forum seem to have went down after 23 May 2018 as the next archived robots.txt state the forum been 'temporary' taken down.

http://web.archive.org/web/20180523152226/http://forum.tampermonkey.net/robots.txt


In any case, it seem I still got my web archive-fu, here the archived link and extract so it can't just disappear and make me look stupid for not including it:

http://web.archive.org/web/20140618103130/http://forum.tampermonkey.net/viewtopic.php?f=21&t=858
> As you may have seen there are some Ads that at the Tampermonkey pages. After now almost 4 years of working on TM (version 1.0 was released on 2010-05-25) this now helps me to offset my expenses and even returns a small amount of profit. Far too small to quit my regular job ;) but it's enough to better start a business to pay taxes to avoid trouble with the german public authorities. So TM is not only a hobby anymore but also has economic and more important legal impacts to me.

http://web.archive.org/web/20140618105736/http://forum.tampermonkey.net/viewtopic.php?f=27&t=81
> You are right, but almost all code that is executed at your computer can be disassembled and is therefore not really closed source. I know there is a tiny difference between disassembling a program and de-obfuscating a javascript, but TMs source is becoming more and more complex with every version, so it will take some time to understand it.
I just want to avoid that once again someone uses my code, repackage and renames it and then ships it with a new name. :(

> Do you have a question related to the way TM is doing something or is there another reason why you're asking for the source?

**Comment by TomasHubelbauer** [comment]
> Do you have a question related to the way TM is doing something or is there another reason why you're asking for the source?

I think this was not meant to be a quote in your comment but rather a question to me, right? If so, the answer is really simple - I just prefer my extensions to be open source. In case of TM I got doubly curious seeing as it wasn't open source _anymore_ meaning at some point it was. I was pretty sure the reason must've been freeloaders taking your work and presenting it as their own, probably with a malicious twice. Same fate that has befallen Paint.NET. Some people just aren't going to be good citizens of the OSS ecosystem. It's depressing to see this lead maintainers to close source their work, but I understand it and empathize with it.

Thanks for digging up the posts!

**Comment by asl97** [comment]
> > Do you have a question related to the way TM is doing something or is there another reason why you're asking for the source?
> 
> I think this was not meant to be a quote in your comment but rather a question to me, right? 
It is part of the quote, as you can see in the comment by derjanb on the archived forum post

**Comment by TomasHubelbauer** [comment]
My bad! Apologies :-)

**Comment by iTrooz** [comment]
Does someone know what the implications of a closed source licence are in this case, since the project was under the GPL before ?

**Comment by Croydon** [comment]
> Does someone know what the implications of a closed source licence are in this case, since the project was under the GPL before ?

If all previous contributors did agree to a re-licensing or their contribution got removed, then it is legally fine

**Comment by pa-0** [comment]
What a strange coincidence that I just happened to click into an issue posing this question when just a few hours ago, I happened to stumble on a thread on HackerNews where the answer is posted (albeit indirectly, so I cannot not speak to the reliability of the source) -- strange because I arrived at both pages with absolutely <ins>no</ins> intention / desire to understand the reasons behind TamperMonkey's open → closed source transition or the related data privacy concerns!  

At any rate, here's what I happened to read earlier today [It's important to know why the three exist, Greasemonkey is the original Firefox... | Hacker News](https://news.ycombinator.com/item?id=26057106#:~:text=It%20would%20be,data%20is%20collected.%22):

<blockquote>

It would be fair to link the developer response: [https://www.reddit.com/r/firefox/comments/6hs59w/tampermonke...](https://www.reddit.com/r/firefox/comments/6hs59w/tampermonkey_has_google_analytics_enabled_by/dj56qpg/)

<div align=justify><blockquote><em><h4>
There is no "they" in Tampermonkey. It's just me, a developer from Germany [...] I don't have the resources that larger companies do have for testing. I have a regular job (40-hour workweek) and besides this, I also spend some time with my wife and my daughter. And finally, and this is the most important one, there are too many unknowns. There are forks of almost every browser, each with slight differences and every new browser version can break things. [...] TL; DR: The Tampermonkey developer needs some data to become aware of bugs happening in the wild. You can disable it. All data is anonymized to the developer. No browsing data is collected.
</h4></em></blockquote></div></blockquote>

<h3>Hopefully, this proves helpful to <em>someone</em> 😁</h3>
