### ISSUE TITLE
Tampermonkey doesn't work with Firefox extension pages.

### ISSUE THREAD

**Issue by AdamEternal** [Tampermonkey/tampermonkey#2228]
## Expected Behavior

I expected that I could use `window.location.href` or `document.URL` in the Firefox console to find the page's URL (since a page from an extension doesn't show a URL in the URL bar), then use that URL in a script's @match.

## Actual Behavior

My script doesn't have any effect, and Tampermonkey's extension icon has no number on it (as it would when it has one or more scripts for that tab).

## Specifications

- Firefox: 132.0.1 (64-bit)
- Tampermonkey: v5.3.1
- OS: Windows 11 Home 23H2 (build 22631.4317)

## Script

This script is trying to match the Firefox extension [Bonjourr](https://github.com/victrme/Bonjourr). It also matches the website version of Bonjourr, where it works as expected. Its purpose is to set the opacity of the settings button to 0.

```js
// ==UserScript==
// @name         Bonjourr
// @namespace    http://tampermonkey.net/
// @version      2024-11-06
// @description  Customize Bonjourr
// @author       You
// @match        https://online.bonjourr.fr/
// @match        moz-extension://1c359164-4b53-4c51-be66-482ba7c25403/index.html
// @icon         https://www.google.com/s2/favicons?sz=64&domain=bonjourr.fr
// @grant        GM_addStyle
// ==/UserScript==

(function() {
    'use strict';

    GM_addStyle(`
        #show-settings {
            opacity: 0;
        }
    `);
})();
```

**Comment by macdevign** [comment]
@match does not work with Chrome extension as well

For example , I have a epub reader extension page in the following address, but Tampermonkey could work with the extension.
extension://gbohfhccchgngoapncnfnpldhlkojifo/

Hopefully the author of Tampermonkey can make it work with extension, because epub reader for example, come in extension.

https://kska32.github.io/beautiful-epub-reader/
### 
![image](https://github.com/user-attachments/assets/23c8f240-8881-4faf-8c57-fa2bd9690857)

**Comment by derjanb** [comment]
Extensions are not allowed to run at other extension's pages, because they could hijack the extension including its permissions.
