### ISSUE TITLE
Education accounts don't seem to be able to authorize OneDrive?

### ISSUE THREAD

**Issue by kingxjs** [Tampermonkey/tampermonkey#2243]
(Please fill out the issue template with your details)

## Expected Behavior
Normal authorization

## Actual Behavior
It will jump to login.live.com for authorization, but education accounts can't log in through login.live.com

## Specifications

- Microsoft Edge: (129.0.2792.65)
- TM: (5.3.2)
- OS: (Windows 10 64-bit)

**Comment by derjanb** [comment]
Yes, because this is the login URL that is stated at the developer docs: https://learn.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth?view=odsp-graph-online#token-flow

So it looks like educational accounts cannot be used to log in to OneDrive Personal:
https://answers.microsoft.com/en-us/msoffice/forum/all/cant-login-to-onedrivelivecom-with-my-college/845ce341-19ef-4bb5-9377-ced1ed3822d9
