### ISSUE TITLE
Can't open dashboard on Safari with latest version

### ISSUE THREAD

**Issue by bebound** [Tampermonkey/tampermonkey#2260]
## Expected Behavior
Clicking dashboard and help button takes no effect. Other buttons are fine.

Upgrade from tampermonkey classic to new app.

<img width="246" alt="Screenshot 2024-11-23 at 15 22 13" src="https://github.com/user-attachments/assets/5a7e4ca6-a547-4933-8a05-1aa4676e153f">

## Actual Behavior
Open dashboard or help website.

## Specifications

- Safari: 18.0.1
- Latest
- OS: MacOS 15.0.1

**Comment by derjanb** [comment]
Hmm, can not reproduce on Sequoia 15.1.1, Safari 18.1.1.

Is it possible to update?

Otherwise: Please to to Safari "Settings" -> "Advanced" and enable "Show features for web developers".
Then inspect Tampermonkey's background page. Do you see errors being logged at this console?

![image](https://github.com/user-attachments/assets/abebbc99-5f21-4e4e-89b2-8411478a8aad)

**Comment by bebound** [comment]
It appears to be fixed in version 5.3.6220, or perhaps macOS 15.1.1 resolves it.

**Comment by derjanb** [comment]
> perhaps macOS 15.1.1 resolves it

Yes, there also were other issues that could be resolved by updating Safari.

**Comment by choudharylakshyaveer** [comment]
I am using the macOS Sequoia Version 15.2 (24C101) and my chrome version is 131.0.6778.140, but still its not woring
