### ISSUE TITLE
it stopped working on opera browser.

### ISSUE THREAD

**Issue by seriousgigi** [Tampermonkey/tampermonkey#2296]
it suddenly stopped working yesterday. when i click to extension endless loading icon appears.

## Specifications

opera Version:99.0.4788.77

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
Tampermonkey's manifest requires Chrome 120 and above. So the opera store should not update to 5.3.6222 at Opera 99 (which is based on Chromium 113). Otherwise this is a bug.

If you want to install Tampermonkey at Opera 99, then please install Tampermonkey Legacy from the Chrome Web store.

https://chromewebstore.google.com/detail/tampermonkey-legacy/lcmhijbkigalmkeommnijlpobloojgfn

**Comment by 11class09** [comment]
Where in opera are the scripts that were uploaded to tampermonkey? How do I get them?
