### ISSUE TITLE
Scripts aren't updating when there's an updated version available

### ISSUE THREAD

**Issue by nickbarry** [Tampermonkey/tampermonkey#242]
1.) What Tampermonkey version do you use? 
3.11

2.) What browser version (go to 'chrome://chrome/') and operating system do
you use?
Chrome 48.0.2535.0 dev-m
Windows 8.1

3.) Does a Userscript cause the problem? If so, from where can it be downloaded?
I don't think it's an issue with a particular script.

4.) Did this work before? Have you checked the script's bug tracker/discussion page for that problem?
I don't think it worked before. I just recently added @downloadURL to each of my scripts, and I haven't noticed if any of them have updated successfully. Before a few days ago, none of them had download URLs, so I ddin't expect any of them to update.
I'm not sure where to find a page reporting this problem. I searched in the Github issues and didn't find anything that seemed to match.

5.) Are there other Userscripts installed and running?
Yes, ~12

6.) Steps to reproduce the problem:
1. I check on the Tampermonkey version of my userscript. It's version 2.
2. I check the version of the script at the downloadURL. It's version 3: https://github.com/nickbarry/pd-helper-userscripts/raw/master/pd-statement-review-helper.user.js
3. I go back to Tampermonkey, and click to update that particular script. It still shows that it is version 2.

7.) What is the expected behavior? What went wrong?
I expect that TM will update the script to the new version.

8.) Please provide any additional information below.
 * In the "Last Updated" column in Tampermonkey, when I click the text ("1m" etc.) to update the script, the text disappears. Sometimes it reappears and is red; other times it doesn't come back. If I refresh the page, the text ("1m" or "2m" etc.) is back, but the script hasn't updated.
 * The Script Update setting is set to "Every hour".

**Comment by derjanb** [comment]
This is working fine here. I installed: 
```https://github.com/nickbarry/pd-helper-userscripts/raw/a14e86e81489db1357a196f750287e9f847c10c0/pd-statement-review-helper.user.js```
and got version 2.0.5 installed.
After enforcing an update script version 4 is downloaded, installed and show at the dashboard.

**Comment by nickbarry** [comment]
Weird. That's not what I'm experiencing. I wonder why my Tampermonkey isn't updating my scripts?

**Comment by derjanb** [comment]
Ok, so let's debug this a little bit. Please open Tampermonkey's background page. Question 600 explains how to get there (http://tampermonkey.net/faq#Q600) but open the network tab instead of the console.
Then try to update your script again. What URL is loaded by TM in order to check for an update and/or get the script code?

**Comment by derjanb** [comment]
Latest TM Beta does have some update related changes which might fix this issue as well. Can you please check this? Thanks.

**Comment by nickbarry** [comment]
@derjanb, thanks, I'll check. What should I do to see if it's working?

**Comment by derjanb** [comment]
Ok, then I'll close this. Just re-open it in case you notice a non-updating script again.

**Comment by Coreda** [comment]
So, I've been experiencing this with a script I have [here](https://github.com/Coreda/neogaf-html5-video). Both FF (using Greasemonkey) and Chromium (using Tampermonkey) were stuck on v1.02, even though v1.1 had been released 17 hours ago. Clicking forced update on each addon did nothing. Last time however v1.01 -> v1.02 updated nearly instantly.

Looked into the network tab in the background.html and it states it checked the correct meta.js file from the metadata header, yet nothing is updated even though the meta.js states v1.1 is the latest.

![tampermonkey auto updates](https://cloud.githubusercontent.com/assets/21355068/18805505/3c79c6b6-8253-11e6-9998-4047e5c24e69.png)

**Comment by derjanb** [comment]
@Coreda this is working fine here. Just installed [this](https://github.com/Coreda/neogaf-html5-video/raw/master/userscript/neogaf-html5-video.user.js), changed the version manually to 1.0 and run a manual update check. After this was done version 1.1 was installed again.

**Comment by Coreda** [comment]
@derjanb not sure what it is, as Tampermonkey on Chromium 53.0.2783.4 still isn't updating the script from v1.02. Neither is Violentmonkey for Opera Presto, and ended up manually re-installing the script for FF Dev version. It's odd.

**Comment by dill0wn** [comment]
> Ok, so let's debug this a little bit. Please open Tampermonkey's background page. Question 600 explains how to get there (http://tampermonkey.net/faq#Q600) but open the network tab instead of the console.
> Then try to update your script again. What URL is loaded by TM in order to check for an update and/or get the script code?

Hey all, I know this is an ancient thread but I have the same issue. But I have a lead!

I followed @derjanb 's steps to investigate the console/network tab, and I think it is a github.com caching issue. I'm not sure it is my local TM instance or github (where I am hosting) that is caching, but the request for my script by background.html is 302'ing to the previous version.

* If I link to `github.com/blah`, background.html 302's to `raw.github.com/blah`, but the content is stale.
* If I link directly to `raw.github.com/blah` in the @updateUrl, the content is still stale
* The content is still stale even if i tick 'disable cache' in background.html's devtools.
* However, if I just wait several minutes, it works.

Leads me to believe my issue is just github's behind-the-scenes caching of direct file fetches. Especially since disabling cahce did nothing, and it looks like the `cache-control` Request Header is set on the force update GET, which seems like it should do something:
```
cache-control: max-age=0, must-revalidate
```

It seems like either way, the update script works, it just isn't immediate.

**Comment by JeromeA** [comment]
I have the same issue with a raw github file, this is still happening: tampermonkey is claiming that there is no update, when there is. A few minutes later, the update works.

My understanding is that all raw requests on github go through a CDN, because they have so many requests for js libraries in particular. There is no way around it, but there are a few ideas that could educate or help the users:

- show a warning that github raw files can be stale by up to 5 minutes
- add a button "retry a few more times" when there is no update, that retries every minute for the next 5 minutes.
- automatically post an update every minute for the next 5 minutes when this happens, with a warning "I'll retry a few more times".
