### ISSUE TITLE
Organize script list in Dashboard via labels or folders

### ISSUE THREAD

**Issue by tophf** [Tampermonkey/tampermonkey#267]
It'd be nice to organize scripts in the list in TM dashboard.

The most intuitive organizational unit is probably a folder but I guess it's not easy to implement so what about an additional `Label` or `Tag` sortable column and an ability to masstag selected scripts?

**Comment by derjanb** [comment]
[The latest beta](http://tampermonkey.net/changelog.php?version=4.2.5336&ext=gcal) got a search/filtering feature. You can make it visible by pressing "Ctrl+f" or checking one of the checkboxes. By default many properties are searched for the given string, but you can also choose a single one.

One of the properties is the "Comment" setting, which can be modified at each script's settings tab. If you now add tags (i.e. #github, #facebook or whatever) to the comment, then you can find and select these scripts by pressing "Ctrl+f" and typing i.e. "#github". "Ctrl+a" then selects all visible scripts. 

I hope this works for you, even though mass tagging it not supported (yet).

**Comment by mxxcon** [comment]
Comment field is a really kludgy way of doing it since I visually can't spot which scripts are not tagged.
I presently have close to 100 different scripts loaded(they are plugins for Ingress' IITC). They are from various authors and origins. And it's getting more and more difficult to try to manage them and keep them organized.
A labeling system where I can quickly see/sort/add/modify by tags/labels would be great.
Also would be useful if script authors to also use this system so that scripts could ship with some labels.

**Comment by Eikosa** [comment]
Was there a date when this feature was coming?

**Comment by PetrKnedlik** [comment]
Yes, I need this so much

**Comment by derjanb** [comment]
Tag support was added at 5.3.6205 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` (after you've enabled 'Developer Mode').

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by cyber-sec0** [comment]
@derjanb 

Why is this closed?

I still can't see the ability to create folders.

This is related to https://github.com/Tampermonkey/tampermonkey/issues/2174#issuecomment-2466066173

@tag, doesn't fold scripts into their tags, so a folder is still needed.

I always have a really hard time trying to find out which script to disable/enable/modify/delete, since I have about 300 scripts for multiple sites.

This folder feature is a dream feature I have had since I started using TM...

@tag has another huge issue, which is that by default TM disabled the auto-update feature on any modified script, so any user who's brave enough to see a script code and add their own tags, will no longer have the script updated again, unless they miraculously know about this, and also know where to go to enable the auto-update feature again.

Another issue is that this depends on either devs being active and nice to add those tags, or users being brave and knowledgeable enough about how to add a tag and that the tag feature does exist, which I doubt that users often read TM documentation or changelogs...

One of the good things about releasing a folder structure system is that any user (non-devs) can easily find it, know what it means, and use it with mouse clicks, without seeing or modifying any code, and without disabling the script auto-update feature without knowing that they're doing that.

**Comment by derjanb** [comment]
Copying over from [here](https://github.com/Tampermonkey/tampermonkey/issues/2174#issuecomment-2466119920) as it describes the feature quite good.

The intended `@tag` workflow might look like this:

1) You installed scripts: 

![image](https://github.com/user-attachments/assets/fd868269-08ac-4a15-adb9-6d3e35951f4d)

2) You want to categorize them, so you add tags to your Tampermonkey

![image](https://github.com/user-attachments/assets/13f5cbbc-4de8-4676-b9ab-be6897f491e5)

3) You assign them to your scripts

![image](https://github.com/user-attachments/assets/d607e62f-1de7-48f8-809f-15a5664ab0d2)

or 

![image](https://github.com/user-attachments/assets/b34e782f-9378-41c1-861d-8a343dce2cce)

4) Now you can filter the scripts by clicking at a tag:

![image](https://github.com/user-attachments/assets/115300fb-2aa6-4ab5-b7f2-a018a10c1998)

5) Bonus: you can enable/disable a tag list at the action menu:

![image](https://github.com/user-attachments/assets/60ba3eab-1bbf-4403-bb0f-ea51e280bfd6)

**Comment by learn2reid** [comment]
would love this!
