### ISSUE TITLE
Fit pages width to width of browser window

### ISSUE THREAD

**Issue by guraga** [Tampermonkey/tampermonkey#286]
Bugs.

> options.html
- You use html tabs. Tabs already realizes by browser. Use browser tabs instead.
- Hard to edit js. There are 4 scroll bars: 2 vertical scroll bars and 2 horizontal scroll bars. Allow use one vertical scroll bar: allow enable word wrap for codepen; allow auto increase height of codepen.
- Do not use horizontal scrolling. Fit window content to width of browser window.

> popup.html
- Allow show one (not two) column.

> User scripts
- Allow set icon to userscript via data: scheme (do not use favicon without user request).
- Allow set icon to menu command via data: scheme.

**Comment by derjanb** [comment]
Since you don't state what TM version you're using I assume it's the Chrome version.

> You use html tabs. Tabs already realizes by browser. Use browser tabs instead.

It's difficult to sync new information between different tabs and also Chrome prefers only one options tab for an extension. Additionally this would make the Android version much more complex. In my opinion the benefits don't compensate for these disadvantages, but you can already open multiple tabs. Just make you don't open the same script twice and don't expect them to sync between each other.

> Hard to edit js. There are 4 scroll bars

The page (when showing a editor tab) requires a resolution of ~1024x700 to work without scrollbars.

> allow enable word wrap for codepen

Can be enabled at the editor settings.

> Allow show one (not two) column.

Can be enabled at the action menu settings.

> Allow set icon to userscript via data: scheme (do not use favicon without user request).

Do you mean the icon of a userscript? Scripts can already set this to whatever they want: http://tampermonkey.net/documentation.php?#_icon

> Allow set icon to menu command via data: scheme.

The usage of this icon is intended, to make it clear that this is a userscript defined menu command.
