### ISSUE TITLE
"Apps, extensions and user scripts cannot be installed from this website"

### ISSUE THREAD

**Issue by JasonBarnabe** [Tampermonkey/tampermonkey#325]
I was trying to install https://greasyfork.org/en/scripts/1-greasemonkey-test-style with Tampermonkey, and it seems to refuse to do so. I end up with Chrome's "Apps, extensions and user scripts cannot be installed from this website." error.

I may have missed the news, but what determines whether Tampermonkey will allow installation?

And could Tampermonkey show its own error in this case rather than confusing me?

**Comment by derjanb** [comment]
The problem is that there neither is a ```@include``` nor a ```@match``` statement. Tampermonkey refuses to install such scripts since version 4.0, because the previous way to interpret no statement as "match all pages" was somehow confusing. Especially if a user checks the script it's not clear that they'll run at every page.

But you're right, I need to find a way to display that error to the user.

**Comment by JasonBarnabe** [comment]
What is the preferred way for scripts to actually "match all pages"?

**Comment by derjanb** [comment]
// @include *
    // @match   *://*/*

Both will do.

**Comment by derjanb** [comment]
I've reverted the change to refuse the installation of such script at [the latest beta version.](http://tampermonkey.net/changelog.php?version=4.2.5330&ext=gcal) Now only a warning is shown at the installation, but the user still has to manually add an ```@include``` to make the script run.
