### ISSUE TITLE
Safari: "@run-at document-start" is broken

### ISSUE THREAD

**Issue by ghost** [Tampermonkey/tampermonkey#344]
My best guess is that this is an upstream issue with Safari itself.

Safari seems to use "lazy" extension loading as a way to reduce the page load delay. So it opens a new tab/window, starts loading the page, and _while_ the page is already loading, it finally loads the extensions.

As a result, "@run-at document-start" doesn't work reliably in Safari. It works somewhat okay (about a 50-75% success rate) while the browser is still under light load. But the succes rate drops to about 10% after the browser has become overloaded and bogged down by lots of tabs/lots of work over time, or lots of videos playing in tabs simultaneously.

It always works in Chrome no matter what, since that browser is smart enough to keep all extensions loaded in memory at all times, and uses a more effective extension code injection method.

I discovered this Safari bug/quirk while developing a userscript. All details are in the info for that script and its excessively elaborate code comments:
https://greasyfork.org/en/scripts/23329-disable-youtube-60-fps-force-30-fps

**Comment by derjanb** [comment]
@SteveJobzniak I do have problems to reproduce this at Safari 10.0.1 and 10.0.2. What version do you use? Also according to [the docs](https://developer.apple.com/library/content/documentation/Tools/Conceptual/SafariExtensionGuide/InjectingScripts/InjectingScripts.html) there should be no lazy loading: 
> "A Start Script executes when the document has been created but before the webpage has been parsed. If your script blocks unwanted content it should be a Start Script, so it executes before the page displays."

and since messaging in Safari is synchronous (in opposition to Chrome) the scripts should be injected at the right moment.

Can you please tell me the messages that Tampermonkey logs to the console after you set the log level to debug and reproduced this issue.

In normal you should see something like this:

    content: normal start event processing for e8b03c4a-3f97-4f32-aa52-13cfc0dc7305 (1 to run)
    content.js:12 content: Start ENV normally e8b03c4a-3f97-4f32-aa52-13cfc0dc7305
    ...
    env: run "Disable YouTube 60 FPS (Force 30 FPS)" ASAP -> document-start
    env: execute script Disable YouTube 60 FPS (Force 30 FPS) @ the unsafe context now
    ...
    content: detected DOMContentLoaded e8b03c4a-3f97-4f32-aa52-13cfc0dc7305

The order of the messages is important. Thanks.

**Comment by SteveJobzniak** [comment]
@derjanb Safari Version 10.0.1 (12602.2.14.0.7) on macOS Sierra 10.12.1.

I disabled all Safari extensions except Tampermonkey and still see the issue.

![screen shot 2016-12-13 at 03 02 57](https://cloud.githubusercontent.com/assets/22373193/21124695/b8cd7930-c0e0-11e6-80e6-67cf8d5a336d.png)

But be aware: The order of messages, and "detected DOMContentLoaded", doesn't mean your extension was actually loaded before the DOM. In fact, it wasn't.

The red bar you see is outputted by my script when it finds "window.ytplayer", which means that YouTube's DOM has already been parsed and its scripts already executed (including the framerate detection code YouTube does, that I am overriding by injecting before its own script runs).

Oh and as I said, it's pretty hard to reproduce this with a freshly started Safari session. It gets much worse after Safari has (or has had) tons of tabs open.

I forgot to say that it's also greatly diminished if you NAVIGATE normally on YouTube by left-clicking on video pages to go to them.

Safari seems to be "the laziest" when you open brand-new tabs.

Here is the most reliable way I know of reproducing it:

- Set Safari Preferences: General: New Windows open with Favorites (I think this matters, because it means no webpage code has a chance to run in the new window, and therefore no chance to inject yet).
- Open a new window (Cmd+N).
- Paste this URL (any video URL works): `https://www.youtube.com/watch?v=CmxkPChOcvw`
- Press Enter.
- Watch the title bar, it will flicker the hash "#fpsreloads=X", which means the script was injected too late and is forcibly reloading the page.
- Tip: If you want to make this even easier, edit the 60fps script and find `if( nextReloadCount <= 2 ) {` and replace it with `if( nextReloadCount <= 0 ) {` to disable the reload-workaround and go straight to the red bar as soon as a tab had Tampermonkey inject too late.

By the way, if Safari really is synchronous, then the bug is in Tampermonkey itself, running start-at document-start scripts too late (perhaps asynchronously). That would be great news because it'd mean it's fixable.

**Comment by derjanb** [comment]
Hi, after updating to Sierra I'm able to reproduce this issue. Unfortunately it's very hard to debug this, so I need a little bit more time. Sorry.

**Comment by SteveJobzniak** [comment]
@derjanb Hi again! That's a good discovery. The issue is indeed much more common in Sierra (compared to Capitan).

As for Stylish, it was a red herring. The author discovered a bug and fixed his code and now it applies styles every time.

What I suggest you try in Tampermonkey: Add some debug code which runs as early as possible in the extension (not in a userscript) and make it look for "window.ytplayer", and if it finds it, display an alert().

If you run with such code and manages to find window.ytplayer it means Safari is loading Tampermonkey after YouTube had already begun building its DOM.

I hope that test fails to find window.ytplayer. Otherwise it's out of Tampermonkey's hands.

**Comment by SteveJobzniak** [comment]
@derjanb I found something else...  I began work on an "auto-Dark Mode" script. And as debug, I added some alerts...

```javascript
// ==UserScript==
// @name         Dark Mode
// @namespace    SteveJobzniak
// @version      1.0
// @description  Dark Mode
// @author       SteveJobzniak
// @match        *://www.youtube.com/*
// @exclude      *://www.youtube.com/tv*
// @exclude      *://www.youtube.com/embed/*
// @run-at       document-start
// @grant        none
// @noframes
// ==/UserScript==

(function() {
    'use strict';

    function enableDark() {
        setTimeout( function() {
            alert('foo');
        }, 200 );
    }

    if( document.readyState === 'complete' ) {
        alert('page already loaded');
        enableDark();
    } else {
        document.addEventListener( 'readystatechange', function( evt ) {
            if( document.readyState === 'complete' ) {
                alert('we were injected before page had finished loading');
                enableDark();
            }
        }, false );
    }
})();
```

If I paste a YouTube URL into the CURRENT Safari tab and press enter, it almost always fires the "we were injected before page had finished loading" alert-box which means that "@run-at document-start" injection happened BEFORE the page had finished loading.

If I do the same but hit Cmd+Enter to open the URL in a BACKGROUND TAB and wait a few seconds to let that background tab download the page, and then switch to the page, I get the "page already loaded" alert.

So it seems like Safari downloads background-tabs and executes their DOM and scripts *WITHOUT* loading any Safari extensions (like Tampermonkey) in that tab until we actually visit the tab.

Alternatively, perhaps you have some Tampermonkey code which is saying "defer processing if tab is in background" which is causing this?

Either way, this discovery seems highly related to this ticket.

**Comment by sethfri** [comment]
It's been about a year since this issue was updated, but I started encountering this quite a bit recently with a script we use at work. Has there been any further investigation into the issue?

**Comment by vyznev** [comment]
I just got a chance to finally test [SOUP](https://github.com/vyznev/soup) with Tampermonkey on Safari and observed the same issue as reported above.  Here's what I see on the console:

```
[Log] content: normal start event processing for 6dcf3526-2e2e-41be-9fc3-6be631b89128 (1 to run) (content.js, line 28)
[Log] content: Start ENV normally 6dcf3526-2e2e-41be-9fc3-6be631b89128 (content.js, line 13)
[Debug] env: initialized (content, id:6dcf3526-2..., https://stackapps.com/questions/4486/the-stack-overflow-unofficial-patch-soup) 
[Log] Tampermonkey started
[Debug] env: run "Stack Overflow Unofficial Patch" ASAP -> document-start
[Debug] env: execute script Stack Overflow Unofficial Patch @ the unsafe context now!
[Log] soup injecting fixes
[Log] soup window.jQuery setter not applied, jQuery has already loaded! (the-stack-overflow-unofficial-patch-soup, line 31)
[Log] soup init complete (the-stack-overflow-unofficial-patch-soup, line 31)
[Log] soup setup complete (the-stack-overflow-unofficial-patch-soup, line 31)
[Log] content: detected DOMContentLoaded 6dcf3526-2e2e-41be-9fc3-6be631b89128 (content.js, line 10)
[Log] soup JS fixes applied (the-stack-overflow-unofficial-patch-soup, line 31)
[Log] soup subscribed to realtime feed for question 4486 on site 101 (the-stack-overflow-unofficial-patch-soup, line 31)
[Log] content: detected load 6dcf3526-2e2e-41be-9fc3-6be631b89128 (content.js, line 10)
```

Note that `soup window.jQuery setter not applied, jQuery has already loaded!` message, indicating that `window.jQuery` is already set by the time SOUP gets a chance to run.

I've tested this with the development version of SOUP (v1.53.1), Safari 11.1 (13605.1.33.1.2) and Tampermonkey v4.5.5661. I get the same output every time I reload the page. I have not yet checked to see if closing all other tabs would make any difference.

**Comment by SteveJobzniak** [comment]
I guess this is an Apple bug due to it lazy-loading extensions in background tabs (not loading extensions until the first time the tab is visited).

In contrast, Google Chrome always runs all extensions in background tabs. I just don't like that as a daily browser. It's too clunky.

**Comment by vyznev** [comment]
@SteveJobzniak This may well be an Apple bug, but it's not (solely) due to lazy-loading extensions in background tabs. At least for me, this bug occurs reliably in foreground tabs too, and indeed even if I only have one single tab open.

Besides, even if this is a Safari bug, IMO it's still something that Tampermonkey should try to work around if at all possible. User scripts that use `@run-at document-start` generally expect to actually run before any content on the page has loaded, and there are things one simply cannot do at any later point.

**Comment by SteveJobzniak** [comment]
@vyznev I completely agree.

**Comment by derjanb** [comment]
Closing because it is related to Safari < 13.
