### ISSUE TITLE
Problem with GM_download

### ISSUE THREAD

**Issue by korridor** [Tampermonkey/tampermonkey#373]
I am using GM_download in my script to download flv video files. (`GM_download({url: url, name: name, saveAs: true});`)
Now I have the problem that the script doesn't show a save-as dialog box, it just starts downloading in the background without showing any download process.
When I change my code to `GM_download({url: url, name: name, saveAs: false});` it does exactly the same thing.
My questions now are:
 - How do I get GM_download to show the download process in the download queue?
 - How do I get GM_download to show a save-as dialog box?

I tested my code in the current version of Firefox and Chrome on several computers.

**Comment by tophf** [comment]
This behavior is customized in Tampermonkey dashboard settings, you need to set it to use the browser API.

**Comment by korridor** [comment]
Thanks! I set the download mode to "Browser API" and now it's working in Chrome, but nothing changed in Firefox.

**Comment by derjanb** [comment]
> you need to set it to use the browser API

Yes, unfortunately TM can't use it by default, because it requires the "download" permission which at the moment is an optional permission that can only be requested on a user action. Making it a default permission would disable TM for every user until it's re-enabled.

> but nothing changed in Firefox

Sorry. When I've implemented this functionality FF threw errors if the details hash contained unknown properties 🙄 and ["saveAs" wasn't supported until version 52](https://bugzilla.mozilla.org/show_bug.cgi?id=1247791). Will be fixed at the next beta version soon.

**Comment by korridor** [comment]
Thanks for the fast help!

**Comment by derjanb** [comment]
Should be fixed now: http://tampermonkey.net/changelog.php?version=4.3.5430&ext=fire
