### ISSUE TITLE
Tampermonkey shouldn't nag for donations if I re-enable the extension after months of having it shut off

### ISSUE THREAD

**Issue by tnorris** [Tampermonkey/tampermonkey#390]
I haven't been using it for a while if it's been disabled the entire time ;)

**Comment by PsyintZ** [comment]
You think that's bad? Recently, mine has started crashing several times a day, and every time I reload it from a full crash - it suggests I donate because I've been using it for a while. Now, this is not a complaint by any stretch - as I'm a huge fan of the extension. I just think that's a pretty awkward time to be asking me for money. Honestly, I wasn't even going to say anything about it, but when I saw your post...

**Comment by derjanb** [comment]
> You think that's bad? Recently, mine has started crashing several times a day, and every time I reload it from a full crash - it suggests I donate because I've been using it for a while.

😂 YMMD

Can you please check the output of the command ```chrome.storage.local.get('#begging', function(d) { console.log(d); });``` run at the extension background page before and after a crash?

I know that the dialog can be annoying, but I try to make it harm as less as possible. Repeated dialogs are not desired.

![image](https://cloud.githubusercontent.com/assets/767504/25500133/1b5b5b40-2b8e-11e7-8e39-fa27c715c757.png)

**Comment by devilman3d** [comment]
How about you DON'T NAG AT ALL??? Been using it for years and now it starts nagging every time I open the dashboard or editor???

**Comment by derjanb** [comment]
Quote from https://github.com/Tampermonkey/tampermonkey/issues/390#issuecomment-297812085

> Repeated dialogs are not desired.

Most probably you browser profile is somehow broken and the information that the dialog was shown gets lost after browser restart.

**Comment by defkev** [comment]
Since I just got hit by the same bullshit, preventing me from literally accessing the dashboard by redirecting to https://www.tampermonkey.net/contrib.php?embedded=2&src=lfire

> [!NOTE]  
> Don't get me wrong! We all have to buy food, pay rent, while spending a shitload of time developing and debugging addons for free, but this is really intrusive and borderline ransomware.

For what's it worth, `first_run` was set to 2 months ago and `dialog/later` to 20 days ago respectively.

1. Open `about:debugging#/runtime/this-firefox` and click the `Inspect` button next to the Tampermonkey extension
2. Copy/paste the following into the `Console` tab and hit return
```js
let today = new Date()
let later = today.setFullYear(today.getFullYear() + 99)
browser.storage.local.set({
    '!extdb.#begging': {
        'origin': 'normal',
        'value': {
            'first_run': {
                'type': 'from_init',
                'ts': later
            },
            'dialog': {
                'ts': later
            },
            'later': {
                'ts': later
            }
        }
    }
})
```
3. Disable and re-enable Tampermonkey in `about:addons`

This will set the time bomb to 99 years in the future, which should theoretically outlast all of use unless the developers decide to change something.
