### ISSUE TITLE
[Firefox] Google Contacts won't fully load with Tampermonkey default settings, disabling CSP setting solves it.

### ISSUE THREAD

**Issue by Kezxo** [Tampermonkey/tampermonkey#391]
If you open https://contacts.google.com while being logged in with Tampermonkey default settings then it won't load fully. Scripts enabled or disabled doesn't matter.
If you disable Tampermonkey it works, or if you disable the **_"Add Tampermonkey to the site's content security policy (CSP) if there is one:"_** setting it also works.

I tested this by downloading Firefox portable if it by chance was just my profile, same result.

Didn't expect TM to mess with sites that I didn't have scripts enabled for, is that really needed?

**Comment by derjanb** [comment]
> Didn't expect TM to mess with sites that I didn't have scripts enabled for, is that really needed?

@Kezxo It isn't, that's why this is already fixed at the [development channel](https://addons.mozilla.org/firefox/downloads/latest-beta/tampermonkey/addon-683490-latest.xpi?src=dp-btn-devchannel). 😉

I've also uploaded this version for review (2017-04-11), but this takes a little longer these days (Queue Position: 176 of 262). 😞
