### ISSUE TITLE
[Firefox] Add option to edit script from UI popup

### ISSUE THREAD

**Issue by Betsy25** [Tampermonkey/tampermonkey#430]
Right now, for scripts that are NOT active, the popup presents a way to report and issue, for script that DO are active, there are no options at all from the popup, It would be nice if it added an easy way to open scripts for editing right from the UI.

Also, the buttons in the main dialog are kinda messy and easy to miss the correct one in the way they are packed together.

**Comment by derjanb** [comment]
> Right now, for scripts that are NOT active, the popup presents a way to report and issue, for script that DO are active, there are no options at all from the popup

This depends on the URL from where the script is installed. If it's one of the known and recognized sources, then an issue report entry will be shown.

> It would be nice if it added an easy way to open scripts for editing right from the UI.

Control+click or middle-mouse-button-click at the script will do the job.

> Also, the buttons in the main dialog are kinda messy and easy to miss the correct one in the way they are packed together.

What is the main dialog? Can you maybe attach a screeshot? Thank.

**Comment by Betsy25** [comment]
Thanks for the quick response, derjanb,
> Control+click or middle-mouse-button-click at the script will do the job

Control+click seems to work here (FF nightly), middle mouse click doesn't.
> What is the main dialog? Can you maybe attach a screeshot? Thank.

Sorry, I was talking about the Dashboard screen, in the Actions column, "Edit" & "Delete" are barely visible with the whitish background. Also, all action buttons are extremely closely stacked together, and look rather clumsy.

**Comment by tophf** [comment]
In the popup right-clicking a script name also invokes the editor.
In the dashboard you can simply click on a script name to open it in the editor.

**Comment by tophf** [comment]
Uhm, you can simply Ctrl-click or Right-click the script in the popup to open it, then switch to its Settings tab. Two clicks. And another one to add an URL.

**Comment by yfdyh000** [comment]
Ctrl-click is looks good, but it is hidden.
I want to have a option and meta option for script, that add a menu item to the script in popup.

**Comment by Betsy25** [comment]
> In the popup right-clicking a script name also invokes the editor.
In the dashboard you can simply click on a script name to open it in the editor.

In the dashboard, right-clicking does work.
In the popup, it doesn't, neither does ctrl-click.

At least not in Firefox 57 with the latest version available for it ( 4.4.5484 )

**Comment by tophf** [comment]
Ctrl-click works for me in FF57. Right-click doesn't because, I guess, FF needs a different event handler in Tampermonkey e.g. `contextmenu` vs `mousedown` vs `auxclick`

BTW, Tampermonkey doesn't open its popup or dashboard in FF57 when its options -> Privacy configured to the notorious "Never remember history" mode, which absurdly disables WebExtensions access to its own secure localStorage, sessionStorage, IndexedDB, except chrome.storage. In Stylus we added try/catch checks on extension start to check these API are working, and if not, fallback to the slower chrome.storage.

**Comment by derjanb** [comment]
> contextmenu vs mousedown vs auxclick 

🙄😁 

Will be fixed at the next release. 

> which absurdly disables WebExtensions access to its own secure localStorage

Yes, Tampermonkey uses localStorage. I'll check if I can make it optional.

**Comment by Betsy25** [comment]
Thanks, right-clicking in the UI now works fine. 👍

**Comment by Betsy25** [comment]
@derjanb 
Using the latest beta 4.5.5570 in Firefox Nightly, rightclick a script in the popup against doesn't open the script in the editor anymore, it simply goes to the script list.

**Comment by joeytwiddle** [comment]
I came here looking for this:

> > It would be nice if it added an easy way to open scripts for editing right from the UI.

> Control+click or middle-mouse-button-click at the script will do the job.

That is great to know! But it was too difficult to discover.

I also think you should add an option to the context menu, on all browsers, so that people can find it easily (without having to read the docs or issues).

You could explain the shortcut in the menu option: _Edit Script (middle-click or Ctrl-click)_

----

(BTW I just made a donation. This extension has been **awesome** for years. It suffered some design problems in the past but these have slowly and surely improved. Thanks and keep up the great work!)
