### ISSUE TITLE
Instant injection mode cookies sometimes break google search

### ISSUE THREAD

**Issue by tophf** [Tampermonkey/tampermonkey#435]
I haven't investigated this, but over the last week or so I've encountered this bug several times. Judging by devtools -> Application -> Cookies, it looks like the cookies aren't expired/removed so eventually google server displays an error page about a malformed request for normal searches from omnibox. It should be noted that I don't restart the browser usually.

Dozens or hundreds of them:
![clip334-fs8](https://user-images.githubusercontent.com/1310400/29470175-12fb0c92-8454-11e7-80f5-ec492b1075a1.png)

Chrome 60.0.3112.90
TM beta 4.4.5533

Today TM updated to 4.4.5541 so I don't know if the issue was fixed.

Sorry for not being able to provide more details.
Can't even tell if this is influenced by some other extension, but I'll try to investigate if you say it's required.

**Comment by derjanb** [comment]
Hmm, it looks like the cleanup mechanism to purge the cookies is (sometimes) not working. I guess the error might be caused by too many cookies. The limit should be somewhere around 180 cookies per domain.

I'll add an expiry date at the next beta to address that.

Sorry for any inconvenience, but (as you know) this is a very experimental option. I even think it will never become the default, because it's that hacky... 😱
