### ISSUE TITLE
Tampermonkey in Android (Chrome) update

### ISSUE THREAD

**Issue by Martii** [Tampermonkey/tampermonkey#437]
So now that I have a phone capable of twiddling with TM I noticed that http://tampermonkey.net/?ext=dhdg&browser=chrome *(or https://play.google.com/store/apps/details?id=net.biniok.tampermonkey as we have it... just did a search for it in google play on the phone)* is out of date *(e.g. 18 vs 60ish something)*.

A few questions from OUJS if you wouldn't mind:

1. Is this app package obsolete/deprecated/ignored/etc.?
2. If not any chance of getting a little newer version published for that pilot study so it's not as vulnerable?

We'll need to update our docs as well for UC and Dolphin now that I know what those are *(Dolphin __not__ related to KDE/Plasma as I had thought in passing ;)*... but need to know what to point to.

Thanks,
OUJS Admin

Btw the app package does work with some of my test scripts *(not all tested)* on Android 7.x so far but barks at me saying the browser *(app package)* is out of date.

**Comment by derjanb** [comment]
Hi @Martii,

yes, the [Tampermonkey app](https://play.google.com/store/apps/details?id=net.biniok.tampermonkey) is out of date, because it's more a pilot study than a real product. The problem is that I'm not good in programming a browser (and this is what the app is and needs to be besides the userscript injection). In my opinion you can ignore this one.

That's why I worked on the [Dolphin version](https://play.google.com/store/apps/details?id=net.tampermonkey.dolphin). Unfortunately their SDK (which is used by Tampermonkey) is sometimes not working with some Dolphin/Android version combinations. I always failed to get support from them.

Another option is the [UC version](https://play.google.com/store/apps/details?id=net.tampermonkey.dolphin) which works quite stable as far as I know.

But my insider tip for userscripts at Android is [Yandex browser (beta)](https://play.google.com/store/apps/details?id=com.yandex.browser.beta). It supports Chrome extensions natively.

**Comment by Martii** [comment]
@derjanb 
So revisiting this again... seems that the link at https://tampermonkey.net/?ext=dhdg&browser=ucweb says:

> We're sorry, the requested URL was not found on this server.

Did it go away?

**Comment by derjanb** [comment]
A year or two ago there was a copyright issue because I used the UC Web icon at the app. I resolved the issue but it looks like the app is still blocked for U.S. visitors 🙄. I also wrote to the initiator of the complaint, because it's the only one that can unblock the app, but I never got a response.
Feel free to remove it from OUJS.
