### ISSUE TITLE
Tampermonkey causes issues when dealing with long URL's

### ISSUE THREAD

**Issue by Royalgamer06** [Tampermonkey/tampermonkey#447]
Contact me for a teamviewer session to debug this. It's hard to explain and reproduce.

**Comment by derjanb** [comment]
There was an issue with the "instant injection mode" some time ago at the beta version. Since none of your reports mentions a Tampermonkey version (1.3.1, mentioned at the is not a valid Tampermonkey version) I'm not sure if you might have used this mode. If this is the root cause, then you need to manually remove all cookies whose name starts with "TM_" from the failing domain.

Otherwise please describe the issue a little bit more in detail. Tell me your Tampermonkey and Chrome version and, if possible, post your script.

Thanks.

**Comment by Royalgamer06** [comment]
Okay, so I resolved my issues. There was this userscript, using the following code:
```
    var open = window.XMLHttpRequest.prototype.open,
        send = window.XMLHttpRequest.prototype.send;

    function openReplacement(method, url, async, user, password) {
        this._url = url;
        return open.apply(this, arguments);
    }

    function sendReplacement(data) {
        if(this.onreadystatechange) {
            this._onreadystatechange = this.onreadystatechange;
        }
        this.onreadystatechange = onReadyStateChangeReplacement;
        return send.apply(this, arguments);
    }

    function onReadyStateChangeReplacement() {
        myCustomFunction();

        if(this._onreadystatechange) {
            return this._onreadystatechange.apply(this, arguments);
        }
    }

    window.XMLHttpRequest.prototype.open = openReplacement;
    window.XMLHttpRequest.prototype.send = sendReplacement;
```

The thing was was weird though, was that this userscript has been DISABLED all this time. Yet, it was able to affect the browser stability and causing it to freeze when dealing with long URL's. Only when this script was completely removed from tampermonkey, all issues would be solved.

**Comment by derjanb** [comment]
> Okay, so I resolved my issues

I'm glad to hear that.

Please also keep in mind, that badly written includes can make Tampermonkey unresponsive (even if the script is disabled):
https://forum.tampermonkey.net/viewtopic.php?f=17&t=2243
https://forum.tampermonkey.net/viewtopic.php?f=17&t=1254
