### ISSUE TITLE
[Suggestion] @-directive or setting for not caching @require scripts?

### ISSUE THREAD

**Issue by rslifka** [Tampermonkey/tampermonkey#475]
I'm doing active development on my @require scripts and TamperMonkey's caching of them makes the development flow lengthy. For every change I have to...

1) Update the script
2) Go to Chrome
3) Find the TM tab with the `Externals` tab selected
4) Press "Delete" on the resource
5) Switch tabs to the page where my UserScript is running
6) Refresh the page

Now if I make a change, my flow is even longer

1) Update the script
2) Go to Chrome
3) Switch back to the TM tab with the `Externals` tab selected.
4) Press refresh (because the Delete button does not appear when the resource is downloaded, you have to refresh the page)
5) Press "Delete" on the resource
6) Switch tabs to the page where my UserScript is running
7) Refresh that page

If there was a directive or TM setting to disable caching, that would be amaaazing. My ideal flow would be:

1) Update the script
2) Go to Chrome
3) Refresh

...and the world would be so much brighter ;)

Perhaps as part of `Advanced` config mode?

**Comment by derjanb** [comment]
There are several ways to ease your pain. :)

1) You can increase the version number before saving the script and all external resources will be reloaded.
2) After setting "Config mode" to "Advanced" you can configure the external update interval. Note: "Always" still means _after_ the resource was used. So you might need to execute/load the page twice.
3) If you use Tampermonkey Beta (Chrome or Firefox) you can edit the external resource in place (because there now is a edit button besides the delete button).
4) Copy the resources and store them locally. After you've enabled "Local file access" at Chrome's extension management page or Tampermonkey's settings page (if you're using Firefox) you can '@require' them via a local file:/// URI.

**Comment by rslifka** [comment]
@derjanb thank you *so much* for the prompt reply with so many options! Re: #4,yes! So file:// resources won't be cached? This would be ideal!

**Comment by derjanb** [comment]
> So file:// resources won't be cached? This would be ideal!

Correct, file:// resources are not cached. The only downside of 4) for scripts using `@run-at document-start` is that local file resources are retrieved asynchronously and therefore the script execution timing might change compared against the usage of cached web resources.

**Comment by rslifka** [comment]
@derjanb my friend, you are a life saver! Option (4) works perfectly. For the testing version of my UserScript I just replaced my resources with file:// versions and it refreshes every time.

Thank you so much. Just made my weekend! :)

**Comment by DanielSmedegaardBuus** [comment]
When did this start being so buggy? Option 2) Doesn't work at all. Set to Always, refresh ad nauseum while keeping making changes and watch the browser (Brave) getting the updated resource every time (with a 200 response instead of 304 for when no changes are made), while the Tampermonkey script never fetches again.

Option 4) worked once, on the first script. With the next script, It keeps console.erroring "Tampermonkey: couldn't load @require from URL file:///Users/daniel/Projects/greasemonkey/my-script-name.js," while the Tampermonkey editor Externals tab lists resources as "0 Byte," no MIME type, and "Subresource Integrity" "<not set>". Again, entering file:///Users/daniel/Projects/greasemonkey/my-script-name.js in a new tab, it loads just fine.

**Comment by MattrCoUk** [comment]
Ive been playing with this a little today (well most of the day lol) First time had a need of injecting local script to a live site.
 @require file:/// doenst seem to work at all, nether on Chrom or FF,
however if you use eg eval() to include js in the settings js it seems to prevent your local scripts to be  cached 
(not tested much)
```

// ==UserScript==
// @name         Local Customisation for Hosting Mattrs
// @namespace    http://tampermonkey.net/
// @version      1.1
// @description  Load local customizations from localhost for Hosting Mattrs
// @author       You
// @match        https://hosting.mattrs.co.uk/*
// @match        https://stackcp.com/*
// @grant        none
// @run-at       document-start
// @require    

// ==/UserScript==


function loadScriptSync(url) {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url, false); // false makes the request synchronous
    xhr.send(null);

    if (xhr.status === 200) {
        eval(xhr.responseText);
    } else {
        console.error(`Error loading script: ${xhr.status} ${xhr.statusText}`);
    }
}

loadScriptSync('http://localhost/app.mattrs.co.uk/hosting-mattrs-cp/app/tampermonkey.js');
```
