### ISSUE TITLE
Donating system error?

### ISSUE THREAD

**Issue by peter17ji** [Tampermonkey/tampermonkey#496]
Tampermonkey BETA 4.6.5694. If I choose to donate 1 RMB by Alipay(支付宝) in the donate pop-up in the dashboard, nothing happens,Stripe pay page won't pop out,and I can't pay it.If I choose more than 6 RMB, it works.Weird.

**Comment by derjanb** [comment]
This is because in this case the fee is higher than the donated amount and you would only send money to the payment processor. :) But you should see a red border around the amount field, do you?

![image](https://user-images.githubusercontent.com/767504/35534521-0ad9dfc0-0541-11e8-9b67-f65a586c0cf4.png)
