### ISSUE TITLE
All my userscripts are randomly gone

### ISSUE THREAD

**Issue by Alice-Cheshire** [Tampermonkey/tampermonkey#536]
When I opened up Firefox (59.0.2 on Windows 10 if it matters) this morning ALL of my userscripts seem to have just disappeared. I found [this](https://github.com/Tampermonkey/tampermonkey/issues/517) closed issue which has the same issue but there was no valid solution there. The only thing I found there was a storage file for another extension.

Hopefully I can recover them somehow because most of my scripts are ones I wrote myself and don't actually have backups for since I wasn't expecting them to randomly disappear like this.

**Comment by derjanb** [comment]
Unfortunately this data corruption is caused by Firefox, which maintains this storage and since extensions only use the provided data storage functionality there is nothing that Tampermonkey can do to prevent this. 

Please double-check your [profile folder](http://kb.mozillazine.org/Profile_folder_-_Firefox). If you really can't find ```browser-extension-data/firefox\@tampermonkey.net/storage.js``` then your scripts are most probably lost (unless you've enabled Dropbox or GDrive sync).

This comment (https://github.com/Tampermonkey/tampermonkey/issues/470#issuecomment-345389658) explains how to use another type of storage called ```localStorage```, but this one has disadvantages as well.

**Comment by Alice-Cheshire** [comment]
Unfortunately they're definitely gone. And while I had GDrive sync enabled at some point in the pt, that somehow got disabled at some point. Thankfully most of them were at least simple scripts so remaking them won't be too big an issue, the real problem is remembering what all of them were since I had quite a few. I've re-enabled GDrive sync so hopefully that'll stay enabled this time.

**Comment by SeAlgoAsoma** [comment]
I do have dropbox sync but can't find my scripts in my drop box. Where are they?

**Comment by derjanb** [comment]
> I do have dropbox sync but can't find my scripts in my drop box. Where are they?

@SeAlgoAsoma https://www.dropbox.com/home/Apps/Tampermonkey
