### ISSUE TITLE
required Scripts not being included

### ISSUE THREAD

**Issue by gituser823** [Tampermonkey/tampermonkey#553]
Hello,

I am using Chrome 66.0.3359.181 x64 and Tampermonkey 4.6

I can't seem to include any external files in my script.

// ==UserScript==
// @name         ScriptZwei
// @namespace    http://mywebsite.com
// @version      0.2
// @description  try to take over the world!
// @author       Me
// @match        http://mywebsite.com/*
// @require      http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @require      https://gist.github.com/raw/2625891/waitForKeyElements.js
// @include      https://mywebsite.com/*
// @grant        none
// ==/UserScript==

`this.$ = this.jQuery = jQuery.noConflict(true);` gives me the Error jQuery is not defined and
`waitForKeyElements ("jNode", actionFunction);` says waitForKeyElements is not defined.

How can I solve this?

In the Extension under Externals the Resources seem to be fine.

**Comment by ssbarnea** [comment]
I think I am facing the same bug with the editor which reports me the "'$' is not defined" but the script runs without problems. This is really annoying for development because the script editor window is full of false warnings about missing jQuery variable.

https://s3.sbarnea.com/ss/180831-Gerrit_Zuul_Status_.png

**Comment by derjanb** [comment]
Simply define you global variables via `globals` comment like this:

```JavaScript
/* globals jQuery, $, waitForKeyElements */
````

**Comment by wrathofodin** [comment]
@derjanb is this documented anywhere?

**Comment by Martii** [comment]
@wrathofodin

>> Simply define you global variables via `globals` comment like this

> ... is this documented anywhere?

See https://jshint.com/docs/options/#globals

**Comment by Hi-Angel** [comment]
@derjanb I am not sure if I misunderstand your comment, but the following code which seems to include your suggestion makes TamperMonkey refuse to even save the script, because it highlights the `waitForKeyElements` call is being undefined:

```javascript
// ==UserScript= =
// @name     Github: load all "hidden items"
// @version  1
// @require https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js
// @require https://gist.githubusercontent.com/BrockA/2625891/raw/9c97aa67ff9c5d56be34a55ad6c18a314e5eb548/waitForKeyElements.js
// @grant    none
// @match    https://github.com/*
/* globals jQuery, $, waitForKeyElements */
// ==/UserScript==
waitForKeyElements('div', (_) => console.log('hello'));
```

I tried adding the `/* globals …` part both in and out of `UserScript` section, as well as tried `//` comment syntax — same behavior.

Pls tell if it's actually a new bug, I will create a new report then. As of now it's just I'm not sure if I'm not missing something.

**Comment by Martii** [comment]
@Hi-Angel 

``` js
// ==UserScript= =
```

I see at least one issue with this line of your UserScript metadata block. Typo?

I'm not using the same `globals` as you but [my example is here](https://openuserjs.org/scripts/Marti/oujs_-_Meta_View). You can check out the Source if you want to for a possible positioning. I don't think it should really matter though but I'm not always in my TM enabled browser testing positioning.

**Comment by Hi-Angel** [comment]
> I see at least one issue with this line of your UserScript metadata block. Typo?

Oh, you are right, thank you!

I was mislead by TamperMonkey pointing at `waitForKeyElements` with "error" highlight. After fixing the typo in header the "error" changed to "warning", and now it works. So apparently there's some problem with interaction of linter with parser.

**Comment by Martii** [comment]
@Hi-Angel 

Been a while since I retested this but apparently it does not like being in-between the lines of the UserScript metadata block like you presented it. Here in Chromium it says `Code found between in metadata` *(bad grammar error message with a red x circle)*

Try putting it outside, with a newline before and after, like I did and it shouldn't bark at you. Working on my example script in TM. 

Good luck! 😄
