### ISSUE TITLE
GM_xmlhttpRequests do not show up in Network Tab of Chrome Inspector

### ISSUE THREAD

**Issue by volkirik** [Tampermonkey/tampermonkey#561]
GM_xmlhttpRequests do not show up in Network Tab of Chrome Inspector

## Expected Behavior
Show all GM_xmlhttpRequests in Network Tab of Chrome Inspector

## Actual Behavior
GM_xmlhttpRequests do not show up in Network Tab of Chrome Inspector

## Specifications

- Chrome: 66.0.3359.181
- TM: v4.6
- OS: Windows NT 10.0; Win64; x64

## Script

Applies to all user-scripts

**Comment by tophf** [comment]
It's performed in the *background page* context.

1. open `chrome://extensions` page
2. enable `developer mode` slider/checkbox
3. click `background` in Tampermonkey's entry.
  (sometimes you'll need to open `details` first - in case several pages are shown in the card).

**Comment by volkirik** [comment]
There is not developer mode slider/checkbox

Do I have to use Chromium instead of Chrome?

**Comment by volkirik** [comment]
They have made userscripts appear at developer tools in version 4.5 (2017-12-30).

I was hoping to see similar change for GM_xmlhttpRequest

**Comment by tophf** [comment]
>There is not developer mode slider/checkbox

Well, Google's designs were always bad, I know, but you can easily find a video or a tutorial that illustrates the procedure. I can show a screenshot:

![chrome_2018-06-10_16-51-00](https://user-images.githubusercontent.com/1310400/41202237-bbeda28e-6cce-11e8-8049-ba3b780fa42d.png)

>They have made userscripts appear at developer tools in version 

Userscripts runs inside the web page but GM_XHR runs inside a different page - the extension's background page, which is why it cannot be shown in web page's devtools.

**Comment by volkirik** [comment]
Thanks so much. Life saver!

**Comment by derjanb** [comment]
@tophf Thanks! :)
