### ISSUE TITLE
Tamper take over Chrome

### ISSUE THREAD

**Issue by arnea-max** [Tampermonkey/tampermonkey#769]
Tamper had take over chrome am had no idea how its come in there. mybe am hacked?
Some organisation had take over my browser and use Tamper.Tried to uninnstall,but no luck.
So what am gone do any idea?

arnea-max

**Comment by derjanb** [comment]
This is caused by a Chrome "feature" that third-party software (which is not related to me) can instruct Chrome to install extensions.

Please check the preferences file and/or Windows registry keys mentioned here: https://developer.chrome.com/extensions/external_extensions#registry and remove them. If they re-appear, then the problematic software is still at your PC.

If you're using Windows the keys are:
32-bit Windows: HKEY_LOCAL_MACHINE\Software\Google\Chrome\Extensions
64-bit Windows: HKEY_LOCAL_MACHINE\Software\Wow6432Node\Google\Chrome\Extensions

Tampermonkey's ID is "dhdgffkkebhmkfjojejmpbldmpobfkfo".
