### ISSUE TITLE
[Firefox] Empty popup

### ISSUE THREAD

**Issue by mikhaelkh** [Tampermonkey/tampermonkey#796]
1. Open new tab
2. Click on extension icon

## Expected Behavior
Normal popup

## Actual Behavior
Empty popup

## Specifications

- Firefox 71.0b5 (64-bit)
- TM: 4.9.6055 beta
- OS: Windows 10 v1607

**Comment by derjanb** [comment]
Hi, this seems to work here. Can you please try a new temporary profile? Is it working then? If yes, then please use your regular profile again otherwise continue with the new temporary profile and go to "about:debugging#/runtime/this-firefox" and press Tampermonkey BETA's Inspect button. 

![image](https://user-images.githubusercontent.com/767504/68049933-65ab9f00-fce4-11e9-8d00-de7e38575fc7.png)

Do you see error messages at the console tab? Does running the command ```scma.clean()``` help?

![image](https://user-images.githubusercontent.com/767504/68050156-d9e64280-fce4-11e9-90bf-5a275f7cfdf6.png)

**Comment by mikhaelkh** [comment]
I can't reproduce it now on FF 71.0b6

**Comment by derjanb** [comment]
OK, let's hope it was a one time issue or b5 was somehow broken. Please re-open if the issues appears again.
