### ISSUE TITLE
Safari - support for macOS 10.13?

### ISSUE THREAD

**Issue by patrickrushton** [Tampermonkey/tampermonkey#854]
Appears that the App Store version requires Catalina (10.14), but seeing as High Sierra (10.13) also updates to Safari 13 it would be great if that OS could also be supported.

**Comment by patrickrushton** [comment]
Oh, I see this question has already been addressed. Shame. Back to the Userscripts extension for me.

**Comment by derjanb** [comment]
After further research I found a way to make Tampermonkey work at 10.13 as well. An updated Tampermonkey version is available at the MacOS App Store already.

However, due to missing Safari/macOS API [1], there are some things that don't work (and most probably won't ever work):

* the menu item icon is not updated even though Tampermonkey runs a this page,
* the menu item has no number that shows how many scripts are running at the current tab
* (programmatically) closing tabs does not always work
* GM_notification does not work

[1]
https://developer.apple.com/documentation/safariservices/sfsafaritab/3075410-close
https://developer.apple.com/documentation/safariservices/sfsafariapplication/3075404-getallwindows
https://developer.apple.com/documentation/safariservices/sfsafariwindow/3075415-getalltabs
https://developer.apple.com/documentation/safariservices/sfsafariextensionviewcontroller/3075407-dismisspopover

**Comment by filbo** [comment]
Safe to assume that there is no hope for 10.12 or earlier?

===

If you wanted to improve 10.13 compatibility (and this is not to imply that you necessarily must want to do so) --

Looking at those docs, there is a getActiveWindow() and getActiveTab(); as we can't see the source, I can only speculate that you _might_ be able to kludge together something using those.

dismissPopover() might be constructable from the parent class (NSViewController)'s removeChild() or removeFromParent() (just guesses from looking at docs -- I have never programmed anything under OS/X).  close() looks less promising based on its inheritance chain, though there's a huge amount of stuff there that I don't have context to understand...

**Comment by ursinus1** [comment]
> After further research I found a way to make Tampermonkey work at 10.13 as well. An updated Tampermonkey version is available at the MacOS App Store already.
> 

This is awesome! I purchased it this morning and it works! Thanks heaps!

**Comment by derjanb** [comment]
> Safe to assume that there is no hope for 10.12 or earlier?

I'm not sure. After switching the compile target to version 10.13 Xcode did not warn me about potential issues and I was forced to tinker with a virtual machine again. This means it's a lot of effort necessary and I'm not sure it's worth it yet.

**Comment by ursinus1** [comment]
hm..on actual testing, well, Tampermonkey work, but safefrom download helper script doesn't for some reason. I thought Tampermonkey works on 10.12? Reason I had to get a 10.13 version is because I was forced to upgrade due to flash drive firmware upgrade.
