### ISSUE TITLE
tampermonkey can't use in new edge

### ISSUE THREAD

**Issue by qqiqqi** [Tampermonkey/tampermonkey#921]
(Please fill out the issue template with your details)
I used to use chrome browser. Recently the edge upgraded, and the tampermonkey was installed automatically. I find the tampermonkey can't run in the new edge browser. It just shows please wait.
## Specifications

- Chromium: (i.e. 64.0.3282.140)
- TM: (i.e. 4.5.5648)
- OS: (i.e. MacOS 10.13.4)

## Script

(Please give an example of the script if applicable.)

```js
// ==UserScript==
// @name MyName
// @namespace http://mywebsite.com
// @Version 1.0
// @description try to take over the world!
// @author Me
// @match http://mywebsite.com/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @include https://mywebsite.com/*
// @grant none
// ==/UserScript==
```

**Comment by derjanb** [comment]
This seems to work fine here. Can you please tell me your Windows 10 and MS Edge version?

**Comment by qqiqqi** [comment]
The version of edge is 81.0.416.64 (interior version of office) (64 bite).
The version of Win10 is Family Chinese 18362.
![image](https://user-images.githubusercontent.com/57854073/80556051-dff37c80-8a04-11ea-95d9-08416bf43ac8.png)
![image](https://user-images.githubusercontent.com/57854073/80556082-fb5e8780-8a04-11ea-92ea-05541e5408fa.png)

**Comment by cuixueqin** [comment]
Encountered the same problem

**Comment by ahong-invitro** [comment]
Encountered the same problem
Browser: Microsoft Edge Chromium 83.0.478.33 beta, 64bit
OS: Win 10 Family Chinese, 64bit (10.0,18362)

**Comment by Sec-ant** [comment]
Encountered the same problem
Browser: Microsoft Edge Chromium 83.0.478.37 beta, 64bit
OS: Win 10 Pro Chinese, 64bit (19041.207)

**Comment by pencilheart** [comment]
Encountered the same problem
Browser: Microsoft Edge Chromium 83.0.478.37 beta, 64bit
OS: Win 10 Pro Chinese, 64bit (10.0 18362)

**Comment by filbo** [comment]
This might be caused by the following:

(1) open https://www.tampermonkey.net, it opens the tab for whatever browser it thinks you have (I don't know what it thinks if you're on Chrome-based Edge)

(2) if it sensibly opens the Chrome tab, user sees and clicks on Microsoft Edge tab, ending up at https://www.tampermonkey.net/?ext=dhdg&browser=edge

(3) the download link there says it's for 'Microsoft Edge >= 31', which matches expectations.  It links to https://microsoft.com/en-us/p/tampermonkey/9nblggh5162s; this is a package for **old** non-Chrome Edge (TM version 4.9.5942).  It has a couple of markers that one might notice, or not: _This is an extension for Microsoft Edge Legacy_ and _Using the new Microsoft Edge? Get extensions from the new Microsoft Edge Addons Store._

(4) TM _also_ exists in the _other_ Edge store: https://microsoftedge.microsoft.com/addons/detail/iikmkjmpaadaobahmlepeloendndfphd (TM version 4.10.6111)

I don't know if new-Edge can successfully install old-Edge extension packages.  If so, who knows what sort of bizarre behavior it might have.

I also don't know (since I'm browsing with Opera on Linux) whether, when running real actual Chrome-based Edge, the TM page instead displays a link to the new package.  But I doubt it.

TO FIX:

- provide dual download buttons on the Microsoft Edge tab
- browser-sniff and highlight the correct one
- clarify the 'Microsoft Edge >= 31' -- Chrome Edge has versions starting in the 70s (I think), so maybe this needs to be >= 31 <= 60' or something; better, 'Legacy Microsoft Edge >= 31' vs. 'Chrome-based Microsoft Edge >= 60' or whatever it needs to be

**Comment by filbo** [comment]
PS: original poster and all 'me too' comments which didn't mention their TM versions ... why?

**Comment by ahong-invitro** [comment]
> This might be caused by the following:
> 
> (1) open https://www.tampermonkey.net, it opens the tab for whatever browser it thinks you have (I don't know what it thinks if you're on Chrome-based Edge)
> 
> (2) if it sensibly opens the Chrome tab, user sees and clicks on Microsoft Edge tab, ending up at https://www.tampermonkey.net/?ext=dhdg&browser=edge
> 
> (3) the download link there says it's for 'Microsoft Edge >= 31', which matches expectations. It links to https://microsoft.com/en-us/p/tampermonkey/9nblggh5162s; this is a package for **old** non-Chrome Edge (TM version 4.9.5942). It has a couple of markers that one might notice, or not: _This is an extension for Microsoft Edge Legacy_ and _Using the new Microsoft Edge? Get extensions from the new Microsoft Edge Addons Store._
> 
> (4) TM _also_ exists in the _other_ Edge store: https://microsoftedge.microsoft.com/addons/detail/iikmkjmpaadaobahmlepeloendndfphd (TM version 4.10.6111)
> 
> I don't know if new-Edge can successfully install old-Edge extension packages. If so, who knows what sort of bizarre behavior it might have.
> 
> I also don't know (since I'm browsing with Opera on Linux) whether, when running real actual Chrome-based Edge, the TM page instead displays a link to the new package. But I doubt it.
> 
> TO FIX:
> 
> * provide dual download buttons on the Microsoft Edge tab
> * browser-sniff and highlight the correct one
> * clarify the 'Microsoft Edge >= 31' -- Chrome Edge has versions starting in the 70s (I think), so maybe this needs to be >= 31 <= 60' or something; better, 'Legacy Microsoft Edge >= 31' vs. 'Chrome-based Microsoft Edge >= 60' or whatever it needs to be

Thank you! TM version 4.10.6111 could be used in the new Microsoft Edge. It seems that when you first use the new Microsoft Edge, it would ask that if you want to synchronize from Chrome. The installed TM is not available in this case.

**Comment by filbo** [comment]
@ahong-invitro are you saying that when TM wasn't working for you, you had not installed TM in Edge?  Rather, when you first used Edge it volunteered to import extensions from Chrome, and it somehow imported a non-functional copy of TM?

**Comment by ahong-invitro** [comment]
@filbo Yes, you could say that. When I installed the new Edge, I had not yet uninstalled Chrome. I may not remember if the browser displays the import option automatically. But I did choose "Import browser data" from Chrome. After that, TM and the other extensions were successfully installed in the new Edge. Somehow, I encountered this problem. After I removed TM and reinstalled it from Microsoft Store, it returned to normal and worked well. 
Thanks again for your help :)

**Comment by derjanb** [comment]
> But I did choose "Import browser data" from Chrome. After that, TM and the other extensions were successfully installed in the new Edge

Tampermonkey from Chrome Webstore should work perfectly fine. The only problem may be that it is signed by Google and not Microsoft.

> TO FIX:
> provide dual download buttons on the Microsoft Edge tab

Thanks, I've updated the page to reflect that TM for Chromium-based MS Edge is not a insider addon anymore.

> OS: Win 10 Family Chinese, 64bit (10.0,18362)
> OS: Win 10 Pro Chinese, 64bit (10.0 18362)
> The version of Win10 is Family Chinese 18362.

This seems to be another kind of problem. Can anybody please check whether it is possible to install Tampermonkey from the new MS addon store: https://microsoftedge.microsoft.com/addons/detail/iikmkjmpaadaobahmlepeloendndfphd

I know there are issues to connect to the Chrome Web Store, most probably due to the great firewall.

Thanks.

**Comment by filbo** [comment]
The video on the Edge landing page is still old-Edge, fwiw.

I think if it were a video only for new-Edge, that'd be fine because anyone actually drilling in there to get TM for old-Edge is doing some sort of special software archaeology project and better be able to think on their feet...

**Comment by derjanb** [comment]
Sure, I hope I'll find the time to make a new one soon. :-)

**Comment by filbo** [comment]
MS changed icons for Edge between legacy & current.  You could use those icons in the two Edge changelog pages, and the Edge download page.  Crude mockup:
![tmp1](https://user-images.githubusercontent.com/3022180/83837129-68bba300-a6aa-11ea-8635-eebb48de7bae.png)

**Comment by ahong-invitro** [comment]
您好，您的邮件已安全抵达我的邮箱，感谢您对我工作的支持。                                         郭窈 呈
