### ISSUE TITLE
Darker theme 'transition: box-shadow' makes font size jump around in Vivaldi

### ISSUE THREAD

**Issue by raszpl** [Tampermonkey/tampermonkey#974]
## Expected Behavior

Consistent font size.

## Actual Behavior

Opening script for the first time you can see font size jump up and back to normal for a split second.
Clicking on text (inside CodeMirror-code) again makes the font size jump up, clicking anywhere else on the page (outside CodeMirror-code), or even outside the browser window makes it go back to normal. Every newly opened script exhibits same behavior exactly ones. Closing and reopening same script wont reproduce the glitch. :o real WTF
Was annoying the hell out of me due to flashing bigger font making lines not fit (even after going back to normal size) ending up adding horizontal scroll bar and eating last line of text. I finally broke down and hunted for a solution :)

Setting Custom CSS:
```
.darker .CodeMirror.cm-s-default,.darker .CodeMirror.cm-s-diff {
    transition: unset !important
}
```
somehow magically fixes things :o 
Is this Browser (Vivaldi) bug? I checked Chrome/Chrome beta and Opera and couldnt reproduce it there.
How would transition even influence font size?!?
Btw why is darker theme manipulating sizes at all? there are font/line size changes etc in the css.

## Specifications

- Vivaldi: 3.1.1929.3 (build on Chrome/83.0.4103.75)
- TM: v4.11.6113 
- OS: W10

**Comment by narcolepticinsomniac** [comment]
Hey, I maintain the darker theme. It's really a personal style I've been using for years, and at some point, Jan decided to include it as an option. It began as a counterpart to my [Stylus theme](https://userstyles.org/styles/142097/stylus-gray-matter), which basically just means they share the same look, and it began with a lot of underlying copypasta styling.

>How would transition even influence font size?!?

I can't repro this particular issue on Win 8.1 with the same versions, but as far as heisenbugs go, regarding transitions and weird visual glitches, this is, and likely always will be, a known Chromium issue. I've seen flickering text and other visual glitches, but never anything as drastic as what you're describing.

Luckily, I don't need to repro, because the property you've pinpointed as being problematic isn't even necessary at all. It's a leftover from a copypasta grabbed from the original style, since Stylus editors show focus via outline/box-shadow.

>Btw why is darker theme manipulating sizes at all? there are font/line size changes etc in the css.

The theme doesn't manipulate those properties in CM. It only alters CM colors if you use the default CM editor theme. Those properties are customized in different areas of the UI for certain elements, because the theme isn't strictly a dark theme. The manager is slightly more compact, and the popup is pretty customized to increase clickable areas and handle overflow better in multi-column modes. At one point, I also tested in a bunch of ancient versions of multiple browsers and tweaked all kinds of properties for compatibility, if that still holds up.

Any future issues can be reported [here](https://github.com/Tampermonkey/tampermonkey-layout) so I'll get a notification. I'll fix this one [there](https://github.com/Tampermonkey/tampermonkey-layout/commit/0716874dfc5d47fd93aca43865f0d36fb32a0df5), and @derjanb will merge it whenever he gets around to it. In the meantime, seems you've hooked up your own workaround.

**Comment by raszpl** [comment]
This must of been vivaldi bug, I was seeing it for maybe couple of months. Upgraded yesterday to `Vivaldi | 3.1.1929.28 (Official Build) (64-bit)`
and it vanished, one day after making this post and finding workaround .. :) :/ For posterity this is how it looked like https://streamable.com/ohbun7

**Comment by derjanb** [comment]
@narcolepticinsomniac Thanks.
