### ISSUE TITLE
Indentation Width setting is ignored

### ISSUE THREAD

**Issue by GrayFace** [Tampermonkey/tampermonkey#984]
I have Indentation Width set to 2 and I indent with Tab characters.
I'm pressing Tab:

## Expected Behavior

Tab character taking the size of 2 spaces.

## Actual Behavior

Tab character takes the size of 4 spaces.

## Specifications

- Chromium: 80.0.3987.163
- TM: 4.10
- OS: Windows

## Script

Any script with tabs.

**Comment by derjanb** [comment]
Should be fixed at TM BETA 4.11.6115

**Comment by w-barath** [comment]
This is not fixed in production versions as of 4.18.1 2022-11-13

Test: 

Set Indentation Width [ 2 ], 
Set Tab Size [ 2 ], 
Set Indent With [ Tabs ]

Editor behaviour:
Indent 4 spaces.
Tab 4 spaces.

Settings Backup behaviour:
Settings not saved.

Closing TamperMonkey tab and re-opening Settings:
Settings not preserved.

**Comment by derjanb** [comment]
Have you pressed the "Save" button at the end of this section?

**Comment by w-barath** [comment]
No, I saved via the settings backup, and hit the restart button at the bottom of the page to apply.

Now I see that button and wonder why I didn't notice it before.  Probably because all the other settings on that page which I've used, have never required hitting a save button.  So ... maybe it would be good if those settings just applied instead of needing to be separately saved, or make it so *all* settings need to be saved so it isn't confusing?   Anyhow thanks for the tip.
