### ISSUE TITLE
safari 13 GM_xhr CORS failed

### ISSUE THREAD

**Issue by kkHAIKE** [Tampermonkey/tampermonkey#989]
## Expected Behavior
GM_xhr onerror event and response is:
status: 408
statusText: "Origin https://ui.tampermonkey.net is not allowed by Access-Control-Allow-Origin."

## Actual Behavior
onload event and everything is ok

## Specifications

- Safari: (i.e. 13.1.1)
- TM: (i.e. 4.10.6108)
- OS: (i.e. MacOS 10.14.6)

## Script
https://github.com/kkHAIKE/fake115/blob/master/fake115.user.js

**Comment by kkHAIKE** [comment]
remove "anonymous: true", every thins be ok....
may be this feature not work in safari

**Comment by derjanb** [comment]
Sorry for the delay. Should be fixed at 4.11.6117.

Please make sure Safari is closed when the update is started.

**Comment by duoluodexiaoxiaoyuan** [comment]
![image](https://user-images.githubusercontent.com/59086082/230700735-ddaca514-a068-4ac2-8170-f49cb1df808e.png)
I want to ask what is the reason for this, because this is a closed source project, but the author's computer can run, I try to report this error on Windows and Mac, I want to ask if this has anything to do with VPN proxy
